name = "Yusuf"
number = 12

[[topics]]
from = 1
to = 111
topic = "KISAH NABI YUSUF "
    [[topics.subs]]
    from = 1
    to = 6
    text = "Yusuf bermimpi"
    [[topics.subs]]
    from = 7
    to = 18
    text = "Yusuf dan saudara-saudaranya"
    [[topics.subs]]
    from = 19
    to = 29
    text = "Yusuf mendapat godaan"
    [[topics.subs]]
    from = 30
    to = 35
    text = "Yusuf dipenjara "
    [[topics.subs]]
    from = 36
    to = 42
    text = "Dakwah Yusuf dalam penjara"
    [[topics.subs]]
    from = 43
    to = 49
    text = "Takwil Yusuf tentang mimpi raja"
    [[topics.subs]]
    from = 50
    to = 57
    text = "Yusuf dibebaskan dari penjara"
    [[topics.subs]]
    from = 58
    to = 93
    text = "Pertemuan Yusuf dengan saudara-saudaranya"
    [[topics.subs]]
    from = 94
    to = 100
    text = "Pertemuan Yusuf A.S. dengan kedua orang tuanya "
    [[topics.subs]]
    from = 101
    to = 101
    text = "Doa Yusuf A.S.  "
    [[topics.subs]]
    from = 102
    to = 111
    text = "Pelajaran yang dapat diambil dari kisah Yusuf A.S. "