name = "Ar-Ra'd"
number = 13

[[topics]]
from = 1
to = 17
topic = "KEBENARAN AL-QUR'AN"
    [[topics.subs]]
    from = 1
    to = 10
    text = "Bukti kekuasaan Allah dan kesempurnaan ilmu-Nya"
    [[topics.subs]]
    from = 11
    to = 11
    text = "Kebangkitan dan keruntuhan suatu bangsa tergantung pada sikap dan tindakan mereka sendiri"
    [[topics.subs]]
    from = 12
    to = 17
    text = "Tanda-tanda keesaan Allah"

[[topics]]
from = 18
to = 29
topic = "MANUSIA MEMPEROLEH BALASAN AMAL PERBUATANNYA"
    [[topics.subs]]
    from = 18
    to = 24
    text = "Beberapa sifat dan perbuatan yang mulia dalam Islam"
    [[topics.subs]]
    from = 25
    to = 27
    text = "Di antara sifat dan perbuatan orang yang ingkar kepada Allah"
    [[topics.subs]]
    from = 28
    to = 29
    text = "Ketenteraman hati orang-orang yang beriman serta pembalasan bagi mereka"

[[topics]]
from = 30
to = 43
topic = "PENGUTUSAN RASUL-RASUL KEPADA UMAT MANUSIA MERUPAKAN SUNNATULLAH"
    [[topics.subs]]
    from = 30
    to = 30
    text = "Allah mengutus Muhammad kepada umatnya sebagaimana Dia mengutus rasul-rasul kepada umat-umat mereka" 
    [[topics.subs]]
    from = 31
    to = 31
    text = "Al-Qur'an kitab yang menggoncangkan dunia"
    [[topics.subs]]
    from = 32
    to = 34
    text = "Penentang Rasul pasti akan hancur"
    [[topics.subs]]
    from = 35
    to = 35
    text = "Gambaran surga"
    [[topics.subs]]
    from = 36
    to = 37
    text = "Orang mukmin menerima keseluruhan Al-Qur'an"
    [[topics.subs]]
    from = 38
    to = 38
    text = "Hidup berkeluarga tidak berlawanan dengan kerasulan"
    [[topics.subs]]
    from = 39
    to = 43
    text = "Tiap-tiap masa memiliki tantangan dan jawabannya sendiri-sendiri"