name = "Al-Anbiyaa"
number = 21

[[topics]]
from = 1
to = 19
topic = "SIKAP KAUM MUSYRIKIN TERHADAP KERASULAN MUHAMMAD SERTA WAHYU YANG DIBAWANYA DAN PENOLAKAN AL-QUR'AN TERHADAPNYA"

[[topics]]
from = 20
to = 47
topic = "BUKTI KESALAHAN KEPERCAYAAN ORANG MUSYRIK"

[[topics]]
from = 48
to = 112
topic = "KISAH BEBERAPA ORANG NABI"
