name = "An-Nuur"
number = 24

[[topics]]
from = 1
to = 64
topic = "HUKUM PERZINAAN DAN PERGAULAN"
    [[topics.subs]]
    from = 1
    to = 3
    text = "Hukum perzinaan"
    [[topics.subs]]
    from = 4
    to = 5
    text = "Hukum menuduh perempuan baik-baik berzina"
    [[topics.subs]]
    from = 6
    to = 10
    text = "Hukum Li'an"
    [[topics.subs]]
    from = 11
    to = 26
    text = "Tuduhan terhadap 'Aisyah Ummul Mukminin"
    [[topics.subs]]
    from = 27
    to = 29
    text = "Pedoman memasuki rumah orang lain"
    [[topics.subs]]
    from = 30
    to = 31
    text = "Pedoman pergaulan antara laki-laki dan perempuan yang bukan mahram"
    [[topics.subs]]
    from = 32
    to = 33
    text = "Anjuran menikah"
    [[topics.subs]]
    from = 34
    to = 35
    text = "Pencerminan ayat-ayat Al-Qur'an sebagai nur Ilahi pada langit dan bumi"
    [[topics.subs]]
    from = 36
    to = 38
    text = "Orang yang mendapat pancaran nur Ilahi"
    [[topics.subs]]
    from = 39
    to = 40
    text = "Orang yang tidak mendapat pancaran nur Ilahi"
    [[topics.subs]]
    from = 41
    to = 46
    text = "Cerminan kekuasaan Allah"
    [[topics.subs]]
    from = 47
    to = 53
    text = "Perbedaan sikap orang munafik dan orang mukmin dalam bertahkim kepada rasul"
    [[topics.subs]]
    from = 54
    to = 57
    text = "Kekuasaan yang dijanjikan Allah kepada orang yang taat dan mengerjakan amal saleh"
    [[topics.subs]]
    from = 58
    to = 61
    text = "Pedoman pergaulan dalam rumah tangga"
    [[topics.subs]]
    from = 62
    to = 64
    text = "Adab pergaulan orang mukmin terhadap Rasul "