name = "Al-Qashash"
number = 28

[[topics]]
from = 1
to = 57
topic = "KISAH MUSA DAN FIR'AUN SEBAGAI BUKTI KEBENARAN AL-QUR'AN"
    [[topics.subs]]
    from = 1
    to = 6
    text = "Kekejaman Fir'aun dan pertolongan Allah kepada Bani Israil"
    [[topics.subs]]
    from = 7
    to = 13
    text = "Musa dicampakkan ke sungai Nil"
    [[topics.subs]]
    from = 14
    to = 19
    text = "Musa diberi ilham dan hikmah sebagai persiapan menjadi rasul"
    [[topics.subs]]
    from = 20
    to = 28
    text = "Musa mendapat nasihat agar meninggalkan negeri Mesir"
    [[topics.subs]]
    from = 29
    to = 32
    text = "Musa pulang ke Mesir dan menerima wahyu untuk menyeru Fir'aun"
    [[topics.subs]]
    from = 33
    to = 37
    text = "Permohonan Musa kepada Allah untuk mengangkat Harun menjadi pembantunya"
    [[topics.subs]]
    from = 38
    to = 42
    text = "Kesombongan Fir'aun"
    [[topics.subs]]
    from = 43
    to = 43
    text = "Taurat diturunkan untuk menjadi petunjuk bagi Bani Israil"
    [[topics.subs]]
    from = 44
    to = 47
    text = "Kisah Musa menerima Taurat hanya diketahui Nabi Muhammad melalui wahyu"
    [[topics.subs]]
    from = 48
    to = 51
    text = "Orang kafir selalu mengingkari bukti sekalipun dahulu meminta"
    [[topics.subs]]
    from = 52
    to = 55
    text = "Sebagian ahli kitab ada yang beriman kepada Muhammad SAW setelah menyaksikan bukti kebenaran"
    [[topics.subs]]
    from = 56
    to = 57
    text = "Hanya Allah yang dapat memberi taufiq untuk beriman"

[[topics]]
from = 58
to = 59
topic = "TUHAN TIDAK AKAN MEMBINASAKAN SESUATU UMAT SEBELUM SEORANG RASUL DIUTUS KEPADA MEREKA"

[[topics]]
from = 60
to = 61
topic = "KEHIDUPAN DUNIAWI ADALAH BAYANGAN DAN KEHIDUPAN AKHIRAT KEKAL DAN ABADI"

[[topics]]
from = 62
to = 67
topic = "PERTANGGUNGJAWABAN PADA HARI KIAMAT"

[[topics]]
from = 68
to = 70
topic = "HANYA ALLAH YANG BERHAK MENENTUKAN SEGALA SESUATU"

[[topics]]
from = 71
to = 73
topic = "BUKTI YANG MENGHARUSKAN KITA MEMUJI ALLAH"

[[topics]]
from = 74
to = 75
topic = "ORANG MUSYRIKIN MEMPERSEKUTUKAN ALLAH KARENA HAWA NAFSU"

[[topics]]
from = 76
to = 82
topic = "KISAH KARUN DAN KEKAYAANNYA ADALAH PELAJARAN BAGI MANUSIA"

[[topics]]
from = 83
to = 84
topic = "SATU KEBAJIKAN DIBALAS BERLIPAT GANDA"

[[topics]]
from = 85
to = 88
topic = "JANJI ALLAH AKAN MEMENANGKAN MUHAMMAD"