name = "Al-'Ankabuut"
number = 29

[[topics]]
from = 1
to = 44
topic = "COBAAN ADALAH BAROMETER BAGI SEMPURNA ATAU TIDAKNYA IMAN SESEORANG"
    [[topics.subs]]
    from = 1
    to = 5
    text = "Cobaan memang diperlukan"
    [[topics.subs]]
    from = 6
    to = 7
    text = "Manfaat usaha manusia kembali kepada dirinya sendiri"
    [[topics.subs]]
    from = 8
    to = 9
    text = "Ajakan mempersekutukan Tuhan harus ditentang sekalipun dari ibu-bapak"
    [[topics.subs]]
    from = 10
    to = 13
    text = "Sikap orang yang lemah iman dalam menghadapi cobaan"
    [[topics.subs]]
    from = 14
    to = 15
    text = "Cobaan terhadap Nabi Nuh"
    [[topics.subs]]
    from = 16
    to = 35
    text = "Cobaan terhadap Nabi Ibrahim dan Nabi Luth"
    [[topics.subs]]
    from = 36
    to = 37
    text = "Cobaan terhadap Nabi Syu'aib"
    [[topics.subs]]
    from = 38
    to = 38
    text = "Cobaan terhadap Nabi Huud dan Nabi Shaleh"
    [[topics.subs]]
    from = 39
    to = 39
    text = "Cobaan terhadap Nabi Musa"
    [[topics.subs]]
    from = 40
    to = 44
    text = "Perlawanan terhadap kebenaran pasti hancur"

[[topics]]
from = 45
to = 55
topic = "AL-QUR'AN MENYUCIKAN JIWA MANUSIA"
    [[topics.subs]]
    from = 45
    to = 45
    text = "Shalat mencegah kejahatan"
    [[topics.subs]]
    from = 46
    to = 52
    text = "Berdebat dengan nonmuslim"
    [[topics.subs]]
    from = 53
    to = 55
    text = "Azab Allah pasti datang pada waktunya"

[[topics]]
from = 56
to = 66
topic = "KEHIDUPAN AKHIRAT ADALAH KEHIDUPAN YANG SEBENARNYA"
    [[topics.subs]]
    from = 56
    to = 59
    text = "Kabar gembira untuk orang yang beriman"
    [[topics.subs]]
    from = 60
    to = 63
    text = "Allah menentukan rezeki setiap makhluk"
    [[topics.subs]]
    from = 64
    to = 66
    text = "Dalam keadaan terdesak manusia mengakui kekuasaan Allah"

[[topics]]
from = 67
to = 69
topic = "JAMINAN ALLAH TERHADAP KEAMANAN TANAH SUCI"
