name = "Al-Ahzab"
number = 33

[[topics]]
from = 1
to = 8
topic = "HUKUM KEKELUARGAAN HARUS BERDASARKAN KETETAPAN ALLAH DAN RASUL"
    [[topics.subs]]
    from = 1
    to = 3
    text = "Takwa dan tawakkal kepada Allah"
    [[topics.subs]]
    from = 4
    to = 5
    text = "Hukum zhihar dan kedudukan anak angkat"
    [[topics.subs]]
    from = 6
    to = 8
    text = "Kedudukan hubungan darah dalam hubungan waris"

[[topics]]
from = 9
to = 25
topic = "BANTUAN ALLAH KEPADA KAUM MUSLIMIN DALAM PERANG AHZAB"

[[topics]]
from = 26
to = 27
topic = "PERANG DENGAN BANI QURAIZHAH"

[[topics]]
from = 28
to = 34
topic = "KETENTUAN ALLAH TERHADAP ISTRI NABI"

[[topics]]
from = 35
to = 36
topic = "SIFAT-SIFAT ORANG MUKMIN DAN KEWAJIBAN MEREKA TERHADAP PERINTAH RASUL"

[[topics]]
from = 37
to = 40
topic = "ANAK ANGKAT TIDAK SAMA DENGAN ANAK KANDUNG"

[[topics]]
from = 41
to = 44
topic = "KEHARUSAN MENGINGAT ALLAH"

[[topics]]
from = 45
to = 48
topic = "MUHAMMAD ADALAH RASUL YANG DIUTUS UNTUK SEGENAP UMAT MANUSIA"

[[topics]]
from = 49
to = 52
topic = "BEBERAPA KETENTUAN ISLAM TENTANG HUKUM PERKAWINAN"
    [[topics.subs]]
    from = 49
    to = 49
    text = "Perempuan yang diceraikan sebelum dicampuri tidak ada 'iddah dan harus diberi mut'ah"
    [[topics.subs]]
    from = 50
    to = 50
    text = "Perempuan yang halal dinikahi oleh Rasul"
    [[topics.subs]]
    from = 51
    to = 51
    text = "Nabi boleh memilih di antara istri-istrinya, siapa yang dipertahankannya dan siapa dilepaskannya"
    [[topics.subs]]
    from = 52
    to = 52
    text = "Nabi tidak boleh menikah lagi setelah ayat ini diturunkan"

[[topics]]
from = 53
to = 58
topic = "ADAB DAN SOPAN SANTUN DALAM RUMAH TANGGA NABI"

[[topics]]
from = 59
to = 59
topic = "KEHARUSAN PEREMPUAN BERJILBAB, JIKA BERADA DI LUAR RUMAH"

[[topics]]
from = 60
to = 62
topic = "ANCAMAN TERHADAP ORANG MUNAFIK DAN ORANG YANG BERBUAT KERUSUHAN DI MADINAH"

[[topics]]
from = 63
to = 63
topic = "HANYA ALLAH YANG MENGETAHUI KAPAN HARI KEBANGKITAN TERJADI"

[[topics]]
from = 64
to = 64
topic = "ANCAMAN TERHADAP ORANG KAFIR"

[[topics]]
from = 69
to = 71
topic = "TAKWA KEPADA ALLAH MEMBAWA PERBAIKAN AMAL DAN AMPUNAN DOSA"

[[topics]]
from = 72
to = 73
topic = "MENERIMA TUGAS TETAPI TIDAK MELAKSANAKANNYA ADALAH KEZALIMAN"
