name = "AL-MU'MIN / Ghafir"
number = 40

[[topics]]
from = 1
to = 85
topic = "PENENTANGAN TERHADAP AGAMA PASTI MENEMUI KEGAGALAN"
    [[topics.subs]]
    from = 1
    to = 6
    text = "Orang-orang mukmin jangan teperdaya oleh kemakmuran orang-orang musyrikin"
    [[topics.subs]]
    from = 7
    to = 9
    text = "Para malaikat bertasbih kepada Allah dan mendoakan orang-orang mukmin"
    [[topics.subs]]
    from = 10
    to = 12
    text = "Keinginan orang-orang kafir keluar dari neraka"
    [[topics.subs]]
    from = 13
    to = 20
    text = "Kewajiban menunaikan ibadah kepada Allah"
    [[topics.subs]]
    from = 21
    to = 55
    text = "Pelajaran yang dapat diambil dari kisah Nabi Musa"
    [[topics.subs]]
    from = 56
    to = 59
    text = "Pengingkaran terhadap kekuasaan Allah hanyalah karena kesombongan semata"
    [[topics.subs]]
    from = 60
    to = 60
    text = "Allah akan memperkenankan doa hamba-Nya"
    [[topics.subs]]
    from = 61
    to = 68
    text = "Kekuasaan Allah yang tercermin pada alam semesta"
    [[topics.subs]]
    from = 69
    to = 77
    text = "Nasib orang yang menentang ayat-ayat Allah dan rasul-Nya"
    [[topics.subs]]
    from = 78
    to = 78
    text = "Rasul ada yang disebutkan kisahnya dalam Al-Qur'an dan ada yang tidak disebutkan"
    [[topics.subs]]
    from = 79
    to = 83
    text = "Pelajaran yang dapat diambil dari peristiwa yang terjadi pada umat-umat terdahulu"
    [[topics.subs]]
    from = 84
    to = 85
    text = "Iman pada waktu azab telah datang tidak berguna lagi"
