name = "Fussilat"
number = 41

[[topics]]
from = 1
to = 8
topic = "NABI ADALAH MANUSIA BIASA YANG DIBERI WAHYU"

[[topics]]
from = 9
to = 12
topic = "ALLAH MENCIPTAKAN LANGIT DAN BUMI DALAM BEBERAPA PERIODE"

[[topics]]
from = 13
to = 18
topic = "PERINGATAN KEPADA KAUM QURAISY TENTANG PERISTIWA YANG DIALAMI KAUM 'AD DAN TSAMUD"

[[topics]]
from = 19
to = 25
topic = "ANGGOTA TUBUH MANUSIA AKAN MENJADI SAKSI PADA HARI KIAMAT"

[[topics]]
from = 26
to = 32
topic = "PEMBALASAN ALLAH TERHADAP ORANG KAFIR DAN ORANG YANG BERIMAN"

[[topics]]
from = 33
to = 54
topic = "AL-QUR'AN ADALAH PETUNJUK DAN PENAWAR"
