name = "Asy-Syuraa"
number = 42

[[topics]]
from = 1
to = 53
topic = "POKOK-POKOK AJARAN PARA RASUL ADALAH SAMA"
    [[topics.subs]]
    from = 1
    to = 4
    text = "Wahyu yang diturunkan kepada Nabi Muhammad sama dengan yang diturunkan kepada rasul-rasul sebelumnya"
    [[topics.subs]]
    from = 5
    to = 6
    text = "Para malaikat memohonkan ampunan kepada Allah untuk penghuni bumi"
    [[topics.subs]]
    from = 7
    to = 9
    text = "Al-Qur'an sebagai peringatan untuk seluruh umat manusia"
    [[topics.subs]]
    from = 10
    to = 12
    text = "Penyelesaian perselisihan umat manusia dikembalikan kepada kitab Allah"
    [[topics.subs]]
    from = 13
    to = 19
    text = "Semua rasul mengajak untuk menyembah Allah Yang Maha Esa"
    [[topics.subs]]
    from = 20
    to = 29
    text = "Allah memberikan balasan amal seseorang menurut niatnya"
    [[topics.subs]]
    from = 30
    to = 37
    text = "Allah memaafkan sebagian besar dosa hamba-Nya"
    [[topics.subs]]
    from = 38
    to = 38
    text = "Kewajiban bermusyawarah tentang masalah keduniaan"
    [[topics.subs]]
    from = 39
    to = 43
    text = "Bersabar dan memberi maaf lebih baik daripada menuntut balas"
    [[topics.subs]]
    from = 44
    to = 50
    text = "Orang yang dibiarkan sesat oleh Allah tidak akan menemukan pemimpin yang memberi petunjuk"
    [[topics.subs]]
    from = 51
    to = 53
    text = "Cara wahyu diturunkan kepada rasul"