name = "Adz-Dzaariyaat"
number = 51

[[topics]]
from = 1
to = 23
topic = "PENEGASAN TENTANG HARI KEBANGKITAN"

[[topics]]
from = 24
to = 60
topic = "KISAH TENTANG UMAT-UMAT TERDAHULU YANG MENDUSTAKAN PARA NABI"
