name = "An-Najm"
number = 53

[[topics]]
from = 1
to = 25
topic = "ALLAH BERSUMPAH BAHWA WAHYU YANG DITURUNKAN KEPADA NABI MUHAMMAD ADALAH BENAR"

[[topics]]
from = 26
to = 30
topic = "CELAAN ALLAH KEPADA KAUM MUSYRIKIN YANG MENGHARAPKAN SYAF'AT DARI MALAIKAT"

[[topics]]
from = 31
to = 32
topic = "ORANG YANG MENJAUHI DOSA BESAR MENDAPAT AMPUNAN DAN BALASAN YANG BAIK"

[[topics]]
from = 33
to = 62
topic = "KEHANCURAN ORANG YANG MENDUSTAKAN KEBENARAN DAN PERTANGGUNGJAWABAN MANUSIA ATAS PERBUATANNYA"
