name = "Al-Jumu'ah"
number = 62

[[topics]]
from = 1
to = 4
topic = "PENGUTUSAN MUHAMMAD ADALAH KARUNIA ALLAH KEPADA MANUSIA"

[[topics]]
from = 5
to = 8
topic = "PERINGATAN KEPADA UMAT ISLAM SUPAYA JANGAN SEPERTI ORANG YAHUDI YANG TIDAK MENGAMALKAN ISI KITAB SUCI"

[[topics]]
from = 9
to = 11
topic = "BEBERAPA HUKUM YANG BERHUBUNGAN DENGAN SHALAT JUM'AT"
