name = "Al-Munafiquun"
number = 63

[[topics]]
from = 1
to = 11
topic = "ORANG-ORANG MUNAFIK"
    [[topics.subs]]
    from = 1
    to = 8
    text = "Sifat-sifat orang munafik"
    [[topics.subs]]
    from = 9
    to = 11
    text = "Peringatan kepada orang-orang mukmin"