name = "At-Taghabun"
number = 64

[[topics]]
from = 1
to = 10
topic = "KESALAHAN MANUSIA AKAN DITAMPAKKAN ALLAH PADA HARI KIAMAT"

[[topics]]
from = 11
to = 18
topic = "BERHATI-HATI TERHADAP KEHIDUPAN DUNIA"