name = "Ath Thalaaq"
number = 65

[[topics]]
from = 1
to = 7
topic = "BEBERAPA KETENTUAN TENTANG TALAK DAN 'IDDAH"

[[topics]]
from = 8
to = 12
topic = "HUKUM-HUKUM YANG DIBAWA NABI MUHAMMAD MEMBAWA KEBAHAGIAAN BAGI MANUSIA"
