name = "Al-Mursalaah"
number = 77

[[topics]]
from = 1
to = 50
topic = "KEADAAN MANUSIA PADA HARI KEPUTUSAN"
    [[topics.subs]]
    from = 1
    to = 26
    text = "Segala ancaman Allah pasti terjadi"
    [[topics.subs]]
    from = 27
    to = 50
    text = "Azab yang ditimpakan kepada orang yang mendustakan kebenaran dan balasan untuk orang yang bertakwa"

