name = "An-Nabaa"
number = 78

[[topics]]
from = 1
to = 40
topic = "HARI KEBANGKITAN"
    [[topics.subs]]
    from = 1
    to = 16
    text = "Kekuasaan Allah menciptakan alam adalah bukti kekuasaan-Nya membangkitkan manusia"
    [[topics.subs]]
    from = 17
    to = 20
    text = "Kedahsyatan hari kebangkitan"
    [[topics.subs]]
    from = 21
    to = 30
    text = "Balasan terhadap orang yang durhaka"
    [[topics.subs]]
    from = 31
    to = 37
    text = "Balasan terhadap orang yang bertakwa"
    [[topics.subs]]
    from = 38
    to = 40
    text = "Perintah agar manusia memilih jalan yang benar kepada Tuhannya"

