name = "At Takwir"
number = 81

[[topics]]
from = 1
to = 14
topic = "KETIKA TERJADI PERISTIWA-PERISTIWA BESAR PADA HARI KIAMAT, SETIAP JIWA TAHU APA YANG TELAH DIKERJAKANNYA DI DUNIA"

[[topics]]
from = 15
to = 29
topic = "MUHAMMAD BUKANLAH SEORANG GILA, TAPI RASUL YANG DITURUNKAN AL-QUR'AN"
