name = "Al-Infitar"
number = 82

[[topics]]
from = 1
to = 9
topic = "CELAAN TERHADAP MANUSIA YANG DURHAKA KEPADA ALLAH"

[[topics]]
from = 10
to = 19
topic = "SEMUA PERBUATAN MANUSIA DICATAT OLEH MALAIKAT DAN AKAN MENDAPAT BALASAN YANG SEIMBANG"
