name = "At-Tariq"
number = 86

[[topics]]
from = 1
to = 4
topic = "SETIAP ORANG ADA YANG MENJAGANYA"

[[topics]]
from = 5
to = 10
topic = "ALLAH KUASA MEMBANGKITKAN MANUSIA"

[[topics]]
from = 11
to = 17
topic = "AL-QUR'AN PEMISAH ANTARA YANG HAQ DAN YANG BATIL"
