name = "Al-Fajr"
number = 89

[[topics]]
from = 1
to = 14
topic = "ORANG YANG MENENTANG NABI MUHAMMAD PASTI BINASA"

[[topics]]
from = 15
to = 20
topic = "KEKAYAAN DAN KEMISKINAN ADALAH UJIAN BAGI HAMBA ALLAH"

[[topics]]
from = 21
to = 26
topic = "PENYESALAN MANUSIA PADA HARI KIAMAT"

[[topics]]
from = 27
to = 30
topic = "PENGHARGAAN ALLAH TERHADAP MANUSIA YANG SEMPURNA IMANNYA"

