name = "At-Tiin"
number = 95

[[topics]]
from = 1
to = 5
topic = "MANUSIA DICIPTAKAN DALAM BENTUK YANG SEBAIK-BAIKNYA "

[[topics]]
from = 6
to = 8
topic = "YANG MENJADI BAROMETER KEMULIAAN IALAH IMAN DAN AMAL "
