name = "Al-Fatihah"
number = 1

[[topics]]
from = 1
to = 1
from = 1
to = 4
topic = "Pujian bagi Allah"

[[topics]]
from = 1
to = 1
from = 5
to = 5
topic = "Pernyataan penghambaan"

[[topics]]
from = 1
to = 1
from = 6
to = 7
topic = "Permintaan untuk mendapatkan jalan yang lurus"

