name = "Yunus"
number = 10

[[topics]]
from = 1
to = 1
topic = "TANDA-TANDA KEBESARAN ALLAH DALAM ALAM SEMESTA"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Wahyu dan dasar-dasar kebenarannya"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Balasan karena mengingkari wahyu"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Manusia adalah satu umat yang memeluk agama yang satu"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perlakuan Allah yang penuh rahmat"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Seruan Allah ke Darussalam dan penolakan terhadapnya "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Bukti-bukti kekuasaan Allah yang membatalkan kepercayaan orang musyrik "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Jaminan Allah tentang kemurnian Al-Qur'an"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Penyesalan manusia di akhirat kelak "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Segala perbuatan manusia tidak lepas dari pengawasan Allah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Wali-wali Allah dan berita gembira bagi mereka "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kisah-kisah Nabi Nuh, Musa, dan Yunus sebagai ibrah bagi manusia"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Dakwah Islam"