name = "Yunus"
number = 10
[[topics]]
from = 1
to = 10
topic = "Tanda-tanda kebesaran Allah dalam alam semesta"

[[topics]]
from = 25
to = 30
topic = "Ajakan masuk surga"

[[topics]]
from = 40
to = 56
topic = "Bukti-bukti kekuasaan Allah yang membatalkan kepercayaan orang"

[[topics]]
from = 57
to = 57
topic = "Al-Qur'an sebagai penyembuh & petunjuk"

