name = "Yunus"
number = 10

[[topics]]
from = 1
to = 109
topic = "TANDA-TANDA KEBESARAN ALLAH DALAM ALAM SEMESTA"
    [[topics.subs]]
    from = 1
    to = 6
    text = "Wahyu dan dasar-dasar kebenarannya"
    [[topics.subs]]
    from = 7
    to = 18
    text = "Balasan karena mengingkari wahyu"
    [[topics.subs]]
    from = 19
    to = 20
    text = "Manusia adalah satu umat yang memeluk agama yang satu"
    [[topics.subs]]
    from = 21
    to = 24
    text = "Perlakuan Allah yang penuh rahmat"
    [[topics.subs]]
    from = 25
    to = 30
    text = "Seruan Allah ke Darussalam (Surga) dan penolakan terhadapnya "
    [[topics.subs]]
    from = 31
    to = 36
    text = "Bukti-bukti kekuasaan Allah yang membatalkan kepercayaan orang musyrik "
    [[topics.subs]]
    from = 37
    to = 53
    text = "Jaminan Allah tentang kemurnian Al-Qur'an"
    [[topics.subs]]
    from = 54
    to = 60
    text = "Penyesalan manusia di akhirat kelak "
    [[topics.subs]]
    from = 61
    to = 61
    text = "Segala perbuatan manusia tidak lepas dari pengawasan Allah"
    [[topics.subs]]
    from = 62
    to = 70
    text = "Wali-wali Allah dan berita gembira bagi mereka "
    [[topics.subs]]
    from = 71
    to = 103
    text = "Kisah-kisah Nabi Nuh, Musa, dan Yunus sebagai ibrah bagi manusia"
    [[topics.subs]]
    from = 104
    to = 109
    text = "Dakwah Islam"