name = "Huud"
number = 11

[[topics]]
topic = "BUKTI-BUKTI KEESAAN DAN KEKUASAAN ALLAH "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perintah menyembah Allah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perbedaan sifat orang kafir dan orang mukmin"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Juz "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kebenaran wahyu "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kisah Nabi Nuh "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kisah Nabi Hud "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kisah Nabi Shaleh "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kisah Nabi Ibrahim dan Nabi Luth "

[[topics]]
topic = "KISAH NABI SYU'AIB "

[[topics]]
topic = "KISAH NABI MUSA "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pelajaran dari kisah-kisah beberapa nabi "