name = "Huud"
number = 11
[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 6
to = 6
topic = "Rezeki semua makhluk sudah dijamin Allah"

[[topics]]
from = 47
to = 49
topic = "Keselamatan seseorang tergantung amalnya"

[[topics]]
from = 114
to = 115
topic = "Perbuatan baik menghapus kesalahan"

