name = "Yusuf"
number = 12
[[topics]]
from = 30
to = 31
topic = "Yusuf dipenjara"

[[topics]]
from = 1
to = 52
topic = "Kisah Nabi Yusuf A.S"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 101
to = 101
topic = "Doa mohon diwafatkan sebagai muslim"

