name = "Ar-Ra'd"
number = 13
[[topics]]
from = 1
to = 10
topic = "kosong"

[[topics]]
from = 11
to = 11
topic = "Kebangkitan dan keruntuhan suatu bangsa tergantung pada sikap dan tindakan mereka sendiri"

[[topics]]
from = 12
to = 17
topic = "kosong"

[[topics]]
from = 18
to = 24
topic = "Mengadakan hubungan silaturahmi merupakan salah satu sifat mulia"

[[topics]]
from = 22
to = 24
topic = "Keluarga yang saleh dapat berjumpa lagi di surga"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 28
to = 29
topic = "Ketentuan hari orang-orang yang beriman serta pembalasan bagi mereka"

[[topics]]
from = 0
to = 0
topic = "kosong"

