name = "Ar-Ra'd"
number = 13

[[topics]]
topic = "KEBENARAN AL-QUR'AN "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Bukti kekuasaan Allah dan kesempurnaan ilmu-Nya"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kebangkitan dan keruntuhan suatu bangsa tergantung pada sikap dan tindakan mereka sendiri"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Tanda-tanda keesaan Allah "

[[topics]]
topic = "MANUSIA MEMPEROLEH BALASAN AMAL PERBUATANNYA "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Beberapa sifat dan perbuatan yang mulia dalam Islam "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Di antara sifat dan perbuatan orang yang ingkar kepada Allah "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Ketenteraman hati orang-orang yang beriman serta pembalasan bagi mereka "

[[topics]]
topic = "PENGUTUSAN RASUL-RASUL KEPADA UMAT MANUSIA MERUPAKAN SUNNATULLAH"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Allah mengutus Muhammad kepada umatnya sebagaimana Dia mengutus rasul-rasul kepada umat-umat mereka" 
    [[topics.subs]]
    from = 1
    to = 1
    text = "Al-Qur'an kitab yang menggoncangkan dunia"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Penentang Rasul pasti akan hancur"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Gambaran surga "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Orang mukmin menerima keseluruhan Al-Qur'an"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Hidup berkeluarga tidak berlawanan dengan kerasulan "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Tiap-tiap masa memiliki tantangan dan jawabannya sendiri-sendiri"