name = "Ibrahim"
number = 14
[[topics]]
from = 1
to = 3
topic = "Al-Qur'an menunjuki semua umat manusia ke jalan yang terang"

[[topics]]
from = 4
to = 7
topic = "Jika bersyukur akan ditambah nikmatnya"

[[topics]]
from = 8
to = 18
topic = "Sikap umat manusia menghadapi ajaran Rasul"

[[topics]]
from = 19
to = 23
topic = "Akibat yang diderita oleh kaum yang menolak kebenaran"

[[topics]]
from = 24
to = 27
topic = "Perumpamaan kalimat yang baik seperti pohon yang baik"

[[topics]]
from = 28
to = 39
topic = "Tindakan-tindakan pemimpin yang menyebabkan kehancuran pengikut-pengikutnya"

[[topics]]
from = 40
to = 40
topic = "Doa agar anak tetap sholat"

[[topics]]
from = 41
to = 41
topic = "Doa agar orangtua diampuni"

[[topics]]
from = 42
to = 45
topic = "Orang yang zalim pasti dapat azab"

[[topics]]
from = 46
to = 51
topic = "kosong"

[[topics]]
from = 52
to = 52
topic = "Al-Qur'an adalah penjelasan yang sempurna"

