name = "Ibrahim"
number = 14

[[topics]]
topic = "WAHYU ILAHI MENGHAPUS KEGELAPAN "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Al-Qur'an menunjukkan semua umat manusia ke jalan yang terang "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Musa A.S. dan rasul-rasul sebelum Nabi Muhammad SAW  adalah pemimpin kaum mereka masing-masing"

[[topics]]
topic = "SIKAP UMAT MANUSIA MENGHADAPI AJARAN RASUL "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kebenaran pada permulaannya ditolak"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Akibat yang diderita oleh kaum yang menolak kebenaran"

[[topics]]
topic = "PENGAKUAN SETAN SETELAH ALLAH MENJATUHKAN KEPUTUSANNYA"

[[topics]]
topic = "YANG TERAKHIR "

[[topics]]
topic = "PERUMPAMAAN TENTANG KEBENARAN DAN KEBATILAN"

[[topics]]
topic = "TINDAKAN PEMIMPIN YANG ENYEBABKAN KEHANCURAN PENGIKUTNYA "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Akibat kufur kepada nikmat Allah serta mempersekutukannya"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perintah Allah untuk mendirikan shalat dan bersedekah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Beberapa nikmat Allah yang dilimpahkan kepada hamba-hamba-Nya "

[[topics]]
topic = "PERMOHONAN NABI IBRAHIM A.S.  "

[[topics]]
topic = "HUKUM TERHADAP PENANTANG ALLAH"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Orang yang zalim pasti mendapat azab"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Segala tipu daya akan gagal "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Juz "