name = "Al-Hijr"
number = 15
[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 45
to = 50
topic = "Rahmat Allah bagi orang-orang yang bertakwa"

[[topics]]
from = 0
to = 0
topic = "kosong"

