name = "An-Nahl"
number = 16
[[topics]]
from = 7
to = 8
topic = "Alam itu merupakan satu kesatuan yang membuktikan kekuasaan Maha Pencipta"

[[topics]]
from = 43
to = 48
topic = "Tiap-tiap umat mempunyai rasul yang diutus untuk menerangkan kebenaran"

[[topics]]
from = 49
to = 50
topic = "Allah Maha Pengampun"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 68
to = 69
topic = "Segi-segi pelajaran yang dapat diambil dari kehidupan alam semesta"

[[topics]]
from = 78
to = 83
topic = "Tidak wajarnya sikap orang-orang musyrik menisbahkan sesuatu kepada Allah"

[[topics]]
from = 90
to = 91
topic = "Perintah berbuat baik"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 98
to = 98
topic = "Adab sebelum membaca Al-Qur'an"

[[topics]]
from = 125
to = 128
topic = "Cara mengajak kepada kebenaran"

