name = "An-Nahl"
number = 16

[[topics]]
from = 1
to = 1
topic = "BUKTI KEBESARAN ALLAH DALAM ALAM SEMESTA"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kepastian hari kiamat dan kebenaran wahyu"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Alam merupakan suatu kesatuan yang membuktikan kekuasaan Allah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Takabur menjadikan seseorang ingkar kepada kebenaran"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Orang yang berbuat tipu daya pasti mengalami kehancuran"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Balasan bagi orang yang bertakwa "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Orang yang binasa karena perbuatannya sendiri "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Setiap umat mempunyai rasul yang diutus untuk menerangkan kebenaran "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Dalam keadaan terjepit, manusia ingat dan kembali kepada Allah "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Orang musyrik menisbatkan sesuatu kepada Allah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pelajaran yang dapat diambil dari alam semesta"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Setiap rasul menjadi saksi atas umatnya pada hari kiamat"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pokok-pokok akhlak yang baik"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Allah lebih mengetahui apa yang bermanfaat dan yang sesuai dengan suatu masa "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Orang yang jauh dari hidayah Allah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Makanan yang halal dan yang haram"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Nabi Ibrahim adalah teladan yang baik"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Dasar-dasar dakwah dan sikap Islam terhadap lawan"
    