name = "Al-Israa"
number = 17
[[topics]]
from = 1
to = 15
topic = "Isyarat kepada umat islam sebagai suatu umat yang akan menjadi besar"

[[topics]]
from = 23
to = 24
topic = "Adab & doa kepada orangtua"

[[topics]]
from = 25
to = 28
topic = "Beberapa tata krama pergaulan"

[[topics]]
from = 29
to = 29
topic = "Jangan terlalu pelit & jangan terlalu pemurah"

[[topics]]
from = 30
to = 32
topic = "Beberapa tata krama pergaulan"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 78
to = 79
topic = "Perintah tahajjud & sholat 5 waktu"

