name = "Al-Kahf"
number = 18

[[topics]]
topic = "Al-Qur'an sebagai bimbingan yang lurus"
from = 1
to = 8

  [[topics.subs]]
  from = 4
  to = 5
  text = "Ancaman terhadap kepercayaan Tuhan punya anak"

[[topics]]
topic = "Kisah Ashabul Kahfi"
from = 9
to = 26

  [[topics.subs]]
  from = 10
  to = 10
  text = "Doa Memohon Rahmat dan Penyempurnaan Petunjuk Dalam Segala Urusan"
  is_dua = true

  [[topics.subs]]
  from = 23
  to = 24
  text = "Etika dalam berjanji"

[[topics]]
topic = "Petunjuk Tentang Dakwah"
from = 27
to = 59

  [[topics.subs]]
  from = 27
  to = 31
  text = "Teguran untuk Nabi agar jangan mementingkan orang terkemuka saja dalam berdakwah"

  [[topics.subs]]
  from = 32
  to = 46
  text = "Perumpamaan kehidupan dunia dan orang yang tertipu olehnya (Kisah pemilik kebun anggur)"

  [[topics.subs]]
  from = 47
  to = 53
  text = "Beberapa kejadian pada hari kiamat dan kedurhakaan iblis"

  [[topics.subs]]
  from = 54
  to = 59
  text = "Akibat tidak mengindahkan peringatan Allah"

[[topics]]
topic = "Kisah Nabi Musa Mencari Ilmu"
from = 60
to = 82

  [[topics.subs]]
  from = 60
  to = 70
  text = "Nabi Musa bertemu dengan Khidir"

  [[topics.subs]]
  from = 71
  to = 73
  text = "Khidhir membocorkan perahu"

  [[topics.subs]]
  from = 74
  to = 76
  text = "Khidhir membunuh seorang anak"

  [[topics.subs]]
  from = 77
  to = 77
  text = "Khidhir membetulkan dinding rumah"

  [[topics.subs]]
  from = 78
  to = 82
  text = "Hikmah di balik perbuatan Khidhir"

[[topics]]
topic = "Kisah Zulkarnain Dengan Ya'juj dan Ma'juj"
from = 83
to = 101

[[topics]]
topic = "Azab Bagi Orang Musyrik dan Pahala Bagi Orang Beriman"
from = 102
to = 108

  [[topics.subs]]
  from = 102
  to = 102
  text = "Celakalah orang musyrik"

  [[topics.subs]]
  from = 103
  to = 106
  text = "Orang yang terperdaya oleh diri sendiri sangat rugi"

  [[topics.subs]]
  from = 107
  to = 108
  text = "Surga Firdaus bagi orang yang beramal saleh"

[[topics]]
topic = "Luasnya Ilmu Allah Tidak Terhingga"
from = 109
to = 110
