name = "Maryam"
number = 19

[[topics]]
topic = "KISAH NABI ZAKARIYA DAN NABI YAHYA"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Penyebab Zakariya berdoa memohon keturunan"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Terkabulnya doa Zakariya sebagai bukti kekuasaan Allah "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pengangkatan Yahya sebagai nabi dan keutamaannya "

[[topics]]
topic = "KISAH MARYAM DAN NABI 'ISA A.S. "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kehamilan Maryam tanpa sentuhan seorang laki-laki"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kelahiran Nabi 'Isa "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Tuduhan terhadap Maryam dan pembelaan Nabi Isa terhadap ibunya"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pertentangan pendapat tentang Isa "

[[topics]]
topic = "KISAH NABI IBRAHIM DENGAN AYAHNYA"

[[topics]]
topic = "KISAH BEBERAPA NABI YANG LAIN "

[[topics]]
topic = "AZAB BAGI ORANG YANG MENENTANG PARA NABI DAN PAHALA BAGI ORANG YANG MENAATINYA"

[[topics]]
topic = "KEPALSUAN AJARAN BAHWA TUHAN MEMPUNYAI ANAK"