name = "Maryam"
number = 19
[[topics]]
from = 1
to = 6
topic = "Kisah Nabi Zakariya AS dan Nabi Yahya AS"

[[topics]]
from = 7
to = 36
topic = "Tuduhan terhadap Maryam dan pembelaan Nabi Isa A.S. kepada ibunya"

[[topics]]
from = 37
to = 65
topic = "Pertentangan pendapat tentang Isa A.S."

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 95
to = 98
topic = "Al-Qur'an dimudahkan dengan bahasamu"

