name = "Surat Al-Baqarah"
number = 2

[[topics]]
topic = "TIGA GOLONGAN MANUSIA DALAM MENGHADAPI AL QUR'AN"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Golongan Mukmin"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Golongan kafir"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Golongan munafik"

[[topics]]
topic = "KEESAAN DAN KEKUASAAN ALLAH "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perintah menyembah Allah Yang Maha Esa"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Tantangan kepada kaum musyrikin mengenai Al Qur'an"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Balasan untuk orang-orang yang beriman "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perumpamaan-perumpamaan dalam Al Qur'an dan hikmah-hikmahnya"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Bukti-bukti kekuasaan Allah "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Penciptaan manusia dan penguasaannya di bumi"

[[topics]]
topic = "PERINGATAN ALLAH KEPADA BANI ISRAIL "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Beberapa perintah dan larangan Allah kepada Bani Israil "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perincian nikmat Allah kepada Bani Israil "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pembalasan terhadap sikap dan perbuatan Bani Israil"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pahala orang yang beriman "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pembalasan terhadap Bani Israil yang melanggar perjanjian dengan Allah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kisah penyembelihan sapi betina"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Keimanan orang Yahudi sukar diharapkan di masa Rasulullah SAW "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Bani Israil mengingkari janjinya dengan Allah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sikap orang Yahudi terhadap para Rasul dan Kitab-kitab yang diturunkan Allah "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Penyembahan yang dilakukan bangsa Yahudi terhadap anak sapi merupakan tanda kecenderungan mereka kepada benda "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Memusuhi Jibril berarti memusuhi Allah yang mengutusnya "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Tuduhan orang Yahudi terhadap Nabi Sulaiman A.S. "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Ketidaksopanan orang-orang Yahudi terhadap Nabi dan sahabat-sahabatnya"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Menasakhkan sesuatu ayat adalah hak Allah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Tindakan-tindakan menghalangi beribadah "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Larangan mengikuti Yahudi dan Nasrani "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perjanjian dengan Nabi Ibrahim A.S. "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Agama Nabi Ibrahim A.S. "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Juz "

[[topics]]
topic = "KEESAAN TUHANLAH YANG AKHIRNYA MENANG"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sekitar pemindahan kiblat"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Cobaan berat dalam menegakkan kebenaran "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Manasik Haji "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Laknat untuk orang-orang yang menyembunyikan ayat-ayat Allah dan orang-orang kafir"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Allah Yang Berkuasa dan Yang menentukan"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Makanan yang halal dan yang haram"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pokok-pokok kebajikan "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Qishash dan hikmahnya"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Wasiat "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Puasa "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Berjihad dengan jiwa dan harta di jalan Allah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Haji "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perbuatan orang-orang munafik "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Hikmah diutusnya para Rasul dan pelbagai cobaan bagi para pengikutnya "

[[topics]]
topic = "BEBERAPA HUKUM SYARIAT"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Orang-orang yang diberi nafkah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Hukum perang dalam Islam"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Khamar, judi, harta yang dinafkahkan dan pemeliharaan anak yatim"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pokok-pokok hukum perkawinan, perceraian dan penyusuan "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kewajiban mengerjakan shalat meskipun dalam keadaan takut"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Wasiat untuk istri dan mut'ah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kewajiban berjihad dan mengeluarkan harta di jalan Allah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Juz "

[[topics]]
topic = "TENTANG RASUL-RASUL DAN KEKUASAAN ALLAH"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Keistimewaan dan perbedaan derajat rasul-rasul "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Anjuran menginfakkan harta"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Ayat Kursi "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Tidak ada paksaan memeluk agama Islam"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Membangkitkan kembali orang-orang yang sudah mati"

[[topics]]
topic = "CARA-CARA PENGGUNAAN HARTA DAN HUKUM-HUKUMNYA"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Menginfakkan harta di jalan Allah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Hukum riba "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kesaksian dalam muamalah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pujian Allah terhadap para mukmin dan doa mereka"