name = "Al-Baqarah"
number = 2
[[topics]]
from = 1
to = 7
topic = "Ciri-ciri golongan mukmin & non-muslim"

[[topics]]
from = 8
to = 20
topic = "Ciri-ciri orang munafik"

[[topics]]
from = 21
to = 24
topic = "Tantangan kepada kaum musyrikin mengenai Qur'an dan perintah menyembah Allah"

[[topics]]
from = 25
to = 25
topic = "Kabar gembira untuk orang beriman"

[[topics]]
from = 26
to = 27
topic = "Perumpamaan-perumpamaan dalam Al-Qur'an dan hikmah-hikmahnya"

[[topics]]
from = 28
to = 29
topic = "Tanda-tanda kekuasaan Allah"

[[topics]]
from = 30
to = 32
topic = "Manusia direncanakan Allah untuk menjadi khalifah"

[[topics]]
from = 33
to = 42
topic = "Kisah Nabi Adam"

[[topics]]
from = 43
to = 44
topic = "Perintah menunaikan sholat dan zakat"

[[topics]]
from = 45
to = 46
topic = "Sabar & sholat sebagai penolong"

[[topics]]
from = 47
to = 48
topic = "kosong"

[[topics]]
from = 49
to = 61
topic = "Perincian nikmat Tuhan kepada Bani Israil"

[[topics]]
from = 62
to = 66
topic = "Kisah Nabi Nuh A.S"

[[topics]]
from = 67
to = 74
topic = "Kisah penyembelihan sapi betina"

[[topics]]
from = 75
to = 82
topic = "Keimanan orang Yahudi sukar diharapkan di masa Rasulullah SAW"

[[topics]]
from = 75
to = 82
topic = "kosong"

[[topics]]
from = 83
to = 91
topic = "Sikap-sikap orang Yahudi terhadap para Rasul dan kitab-kitab yang diturunkan Allah"

[[topics]]
from = 92
to = 101
topic = "Penyembahan yang dilakukan bangsa Yahudi terhadap anak sapi, merupakan lambang bagi kecendrungan mer"

[[topics]]
from = 102
to = 115
topic = "Menasakhkan sesuatu ayat adalah urusan Allah"

[[topics]]
from = 116
to = 123
topic = "Larangan mengikuti Yahudi dan Nasrani"

[[topics]]
from = 124
to = 127
topic = "Kisah Nabi Ibrahim & Kota Mekkah"

[[topics]]
from = 128
to = 129
topic = "Do'a menjadi seorang muslim"

[[topics]]
from = 130
to = 149
topic = "Sekitar pemindahan kiblat"

[[topics]]
from = 150
to = 152
topic = "Perintah berserah & mengingat Allah dimana saja"

[[topics]]
from = 153
to = 157
topic = "Allah beserta orang sabar"

[[topics]]
from = 158
to = 158
topic = "Sa'i & Manasik Haji"

[[topics]]
from = 159
to = 171
topic = "Laknat terhadap orang-orang yang menyembunyikan ayat-ayat Allah dan terhadap orang-orang kafir"

[[topics]]
from = 172
to = 173
topic = "Perintah memakan makanan yang halal"

[[topics]]
from = 174
to = 176
topic = "Ayat-Ayat Allah"

[[topics]]
from = 177
to = 177
topic = "Kebajikan adalah urusan akhirat, bukan duniawi"

[[topics]]
from = 178
to = 179
topic = "Qisas dan hikmahnya"

[[topics]]
from = 180
to = 182
topic = "Wasiat & larangan mengubahnya"

[[topics]]
from = 186
to = 186
topic = "Allah Maha Dekat"

[[topics]]
from = 187
to = 194
topic = "Berjihad dengan Jiwa & Harta"

[[topics]]
from = 187
to = 194
topic = "Berjihad dengan Jiwa & Harta"

[[topics]]
from = 195
to = 195
topic = "Perintah untuk berinfaq di jalan Allah"

[[topics]]
from = 196
to = 199
topic = "Haji"

[[topics]]
from = 200
to = 201
topic = "Doa kebaikan dunia & akhirat"

[[topics]]
from = 202
to = 214
topic = "Perbuatan orang-orang munafik"

[[topics]]
from = 215
to = 215
topic = "Infak & sedekah"

[[topics]]
from = 216
to = 216
topic = "Kebaikan di balik yang tidak kita sukai"

[[topics]]
from = 217
to = 220
topic = "Hukum perang dalam Islam"

[[topics]]
from = 221
to = 232
topic = "Pokok-pokok hukum perkawinan, perceraian dan penyusuan"

[[topics]]
from = 233
to = 233
topic = "Anjuran menyusui anak selama 2 tahun"

[[topics]]
from = 234
to = 237
topic = "Hukum Perceraian,"

[[topics]]
from = 238
to = 242
topic = "Kewajiban mengerjakan salat walaupun dalam keadaan takut"

[[topics]]
from = 243
to = 251
topic = "Jihad di Jalan Allah"

[[topics]]
from = 252
to = 252
topic = "Kebenaran Muhammad Adalah Rasulullah"

[[topics]]
from = 253
to = 254
topic = "Keistimewaan dan perbedaan derajat para Rasul dan anjuran berjihad dengan harta"

[[topics]]
from = 256
to = 257
topic = "Tak ada paksaan dalam mempelajari agama Islam"

[[topics]]
from = 258
to = 260
topic = "Kisah Nabi Ibrahim & Mukjizatnya"

[[topics]]
from = 261
to = 263
topic = "Menafkahkan harta di jalan Allah"

[[topics]]
from = 264
to = 270
topic = "Sedekah"

[[topics]]
from = 271
to = 271
topic = "Mencontohkan sedekah itu baik, menyembunyikannya lebih baik"

[[topics]]
from = 272
to = 281
topic = "Hukum Riba"

[[topics]]
from = 282
to = 283
topic = "Kesaksian dalam mu'amalah"

[[topics]]
from = 284
to = 286
topic = "Doa orang mukmin"

