name = "Tahaa"
number = 20

[[topics]]
from = 1
to = 1
topic = "AL-QUR'AN DITURUNKAN SEBAGAI PERINGATAN BAGI MANUSIA"

[[topics]]
from = 1
to = 1
topic = "KISAH NABI MUSA"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Nabi Musa menerima permulaan wahyu "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Dua macam mukjizat Musa"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perintah Allah kepada Nabi Musa dan permohonan Nabi Musa"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Nikmat Allah kepada Nabi Musa sejak kecil"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Musa dan Harun diperintah menghadap Fir'aun "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Nabi Musa menundukkan tukang sihir Fir'aun"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Tukang sihir Fir'aun menjadi orang yang beriman"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pembelahan laut dan pembebasan Bani Israil "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Teguran Allah kepada Nabi Musa"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pengkhianatan Samiri"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Teguran Musa kepada Harun dan balasan Harun"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Hardikan Musa terhadap Samiri"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Azab yang ditimpakan kepada Samiri"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kisah umat-umat terdahulu merupakan peringatan bagi manusia"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Keadaan pada hari kiamat"

[[topics]]
from = 1
to = 1
topic = "KISAH NABI ADAM DAN PEMBANGKANGAN IBLIS"

[[topics]]
from = 1
to = 1
topic = "BEBERAPA PERINGATAN DAN AJARAN TENTANG MORAL"