name = "Tohaa"
number = 20
[[topics]]
from = 1
to = 24
topic = "Perintah Allah kepada Nabi Musa A.S. dan permohonan Nabi Musa A.S."

[[topics]]
from = 25
to = 28
topic = "Doa mempermudah urusan"

[[topics]]
from = 29
to = 41
topic = "Ni'mat-ni'mat Allah kepada Nabi Musa A.S. sejak kecil"

[[topics]]
from = 112
to = 114
topic = "Hak orang beriman dan diturunkannya Al Qur'an dengan bahasa Arab"

[[topics]]
from = 132
to = 135
topic = "kewajiban suami mengajak keluarganya sholat"

