name = "Al-Anbiyaa"
number = 21

[[topics]]
topic = "SIKAP KAUM MUSYRIKIN TERHADAP KERASULAN MUHAMMAD SERTA WAHYU YANG DIBAWANYA DAN PENOLAKAN AL-QUR'AN TERHADAPNYA"

[[topics]]
topic = "BUKTI KESALAHAN KEPERCAYAAN ORANG MUSYRIK "

[[topics]]
topic = "KISAH BEBERAPA ORANG NABI"
