name = "Al-Hajj"
number = 22

[[topics]]
topic = "KEHIDUPAN PADA HARI AKHIR"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kedahsyatan hari kiamat "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Celaan terhadap orang yang membantah Tuhan "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Proses kejadian manusia dan tumbuh-tumbuhan adalah bukti yang nyata tentang kebenaran hari kebangkitan"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Celaan terhadap orang yang membantah Tuhan karena kesombongan "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Celaan terhadap orang yang tidak memiliki pendirian"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Balasan terhadap orang yang beriman dan beramal saleh"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pertolongan Allah pasti datang"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Keadaan orang kafir di dalam neraka dan balasan untuk orang yang beriman"

[[topics]]
topic = "HAJI, MANASIK DAN SYI'ARNYA"

[[topics]]
topic = "IZIN BERPERANG BAGI ORANG-ORANG MUKMIN"

[[topics]]
topic = "AYAT-AYAT ALLAH SEBAGAI PENGHIBUR NABI MUHAMMAD "

[[topics]]
topic = "TUGAS RASUL ADALAH MEMBERI PERINGATAN"

[[topics]]
topic = "BALASAN UNTUK ORANG YANG MATI DALAM HIJRAH DI JALAN ALLAH"

[[topics]]
topic = "NIKMAT ALLAH YANG DIBERIKAN KEPADA MANUSIA"

[[topics]]
topic = "SETIAP UMAT MEMPUNYAI SYARIAT TERTENTU "

[[topics]]
topic = "KELEMAHAN PENDIRIAN ORANG KAFIR DALAM MENYEMBAH SELAIN ALLAH "

[[topics]]
topic = "AGAMA ISLAM BUKANLAH AGAMA YANG SEMPIT"