name = "Al-Hajj"
number = 22
[[topics]]
from = 11
to = 13
topic = "Celaan terhadap orang-orang yang tidak berpendirian"

[[topics]]
from = 15
to = 17
topic = "Pertolongan Allah pasti datang"

[[topics]]
from = 18
to = 18
topic = "Semua bersujud kepada Allah"

[[topics]]
from = 26
to = 28
topic = "Haji, Menasiknya, & Syi'arnya"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 58
to = 62
topic = "Balasan terhadap orang-orang yang mati dalam berhijrah di jalan Allah"

