name = "Al-Mu'minuun"
number = 23

[[topics]]
topic = "KEMENANGAN ORANG MUKMIN "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Tujuh sifat yang menjadikan orang mukmin beruntung "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perkembangan kejadian manusia "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Langit dan segala sesuatu yang ada di bumi, diciptakan Allah untuk kelanjutan hidup manusia dan wajib disyukuri"

[[topics]]
topic = "KISAH BEBERAPA ORANG RASUL "

[[topics]]
topic = "AGAMA YANG DIBAWA NABI-NABI ADALAH SAMA "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Hawa nafsu memecah belah manusia"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sifat-sifat seorang muslim yang mukhlis"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kewajiban menjalankan agama sesuai dengan kemampuan"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Celaan dan azab yang diancamkan terhadap orang kafir"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Meskipun dalil-dalil tentang kebangkitan di akhirat cukup banyak, namun orang kafir tetap mengingkarinya "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sanggahan terhadap pendirian orang kafir, terutama anggapan bahwa Tuhan mempunyai anak atau sekutu "

    [[topics.subs]]
    from = 1
    to = 1
    text = "Doa agar tidak dimasukkan ke dalam golongan orang zalim, pedoman dalam menghadapi lawan dan perintah berlindung dari godaan setan"

    [[topics.subs]]
    from = 1
    to = 1
    text = "Peristiwa-peristiwa pada hari kiamat dan kedahsyatannya "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Tuhan menciptakan manusia bukan sia-sia "
    