name = "Al-Mu'minuun"
number = 23
[[topics]]
from = 1
to = 11
topic = "Ciri-ciri orang mukmin"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 17
to = 22
topic = "Langit dan segala sesuatu yang ada di bumi, diciptakan oleh Allah untuk kelanjutan kehidupan manusia"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 57
to = 61
topic = "Sifat-sifat seorang muslim yang mukhlis"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 95
to = 114
topic = "Peristiwa-peristiwa pada hari Kiamat dan kedahsyatannya"

[[topics]]
from = 115
to = 118
topic = "Penciptaan manusia tidak sia-sia"

