name = "An-Nuur"
number = 24
[[topics]]
from = 1
to = 20
topic = "Tuduhan yang bohong terhadap Aisyah R.A., Ummul Mu'minun"

[[topics]]
from = 21
to = 25
topic = "kosong"

[[topics]]
from = 26
to = 26
topic = "Wanita baik untuk lelaki baik & sebaliknya"

[[topics]]
from = 30
to = 31
topic = "Adat berpakaian bagi laki2 & perempuan"

[[topics]]
from = 35
to = 38
topic = "Allah pemberi cahaya langit & bumi"

[[topics]]
from = 0
to = 0
topic = "kosong"

