name = "Al-Furqan"
number = 25
[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 63
to = 66
topic = "Hamba Allah adalah yang berjalan di bumi dengan rendah hati"

[[topics]]
from = 74
to = 74
topic = "Doa memohon pasangan & keturunan"

[[topics]]
from = 0
to = 0
topic = "kosong"

