name = "Asy-Syu'ara"
number = 26

[[topics]]
topic = "NABI MUHAMMAD TIDAK PERLU BERSEDIH ATAS KEINGKARAN KAUM MUSYRIKIN "

[[topics]]
topic = "KISAH NABI MUSA "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perintah Tuhan kepada Nabi Musa untuk menyeru Fir'aun"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Tanya jawab antara Musa dan Fir'aun"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perintah Tuhan kepada Musa untuk menyelamatkan Bani Israil dan pembinasaan Fir'aun"

[[topics]]
topic = "KISAH IBRAHIM "

[[topics]]
topic = "KISAH NUH DENGAN KAUMNYA"

[[topics]]
topic = "KISAH HUUD "

[[topics]]
topic = "KISAH SHALEH "

[[topics]]
topic = "KISAH LUTH DENGAN KAUMNYA"

[[topics]]
topic = "KISAH SYU'AIB "

[[topics]]
topic = "AL-QUR'AN DITURUNKAN KEPADA NABI MUHAMMAD DALAM BAHASA ARAB"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perintah memberi peringatan kepada keluarga dan bersikap lemah-lembut terhadap orang mukmin"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Setan turun kepada pembohong dan peringatan terhadap penyair "
