name = "An-Naml"
number = 27

[[topics]]
topic = "AL-QUR'AN PEDOMAN HIDUP DAN BERITA GEMBIRA BAGI ORANG MUKMIN"

[[topics]]
topic = "MUSA MENERIMA WAHYU, DAN MUHAMMAD PUN MENERIMA WAHYU AL-QUR'AN"

[[topics]]
topic = "KISAH NABI DAWUD DAN NABI SULAIMAN "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sulaiman mewarisi kerajaan Dawud "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pembicaraan Sulaiman dengan burung Hud-hud "

[[topics]]
topic = "PELAJARAN DARI KEINGKARAN KAUM SHALEH"

[[topics]]
topic = "PERBUATAN CABUL KAUM LUTH "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Juz "

[[topics]]
topic = "PERINTAH ALLAH KEPADA MUHAMMAD UNTUK MENSYUKURI NIKMAT "

[[topics]]
topic = "ORANG KAFIR MENGINGKARI HARI KEBANGKITAN"

[[topics]]
topic = "AL-QUR'AN BUKTI KENABIAN MUHAMMAD "

[[topics]]
topic = "TANDA-TANDA KEDATANGAN HARI KIAMAT"