name = "Al-Qashash"
number = 28

[[topics]]
from = 1
to = 1
topic = "KISAH MUSA DAN FIR'AUN SEBAGAI BUKTI KEBENARAN AL-QUR'AN"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kekejaman Fir'aun dan pertolongan Allah kepada Bani Israil"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Musa dicampakkan ke sungai Nil"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Musa diberi ilham dan hikmah sebagai persiapan menjadi rasul"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Musa mendapat nasihat agar meninggalkan negeri Mesir"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Musa pulang ke Mesir dan menerima wahyu untuk menyeru Fir'aun"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Permohonan Musa kepada Allah untuk mengangkat Harun menjadi pembantunya"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kesombongan Fir'aun "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Taurat diturunkan untuk menjadi petunjuk bagi Bani Israil"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kisah Musa menerima Taurat hanya diketahui Nabi Muhammad melalui wahyu"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Orang kafir selalu mengingkari bukti sekalipun dahulu meminta"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sebagian ahli kitab ada yang beriman kepada Muhammad SAW setelah menyaksikan bukti kebenaran "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Hanya Allah yang dapat memberi taufiq untuk beriman"

[[topics]]
from = 1
to = 1
topic = "TUHAN TIDAK AKAN MEMBINASAKAN SESUATU UMAT SEBELUM SEORANG"

[[topics]]
from = 1
to = 1
topic = "RASUL DIUTUS KEPADA MEREKA"

[[topics]]
from = 1
to = 1
topic = "KEHIDUPAN DUNIAWI ADALAH BAYANGAN DAN KEHIDUPAN AKHIRAT KEKAL DAN ABADI"

[[topics]]
from = 1
to = 1
topic = "PERTANGGUNGJAWABAN PADA HARI KIAMAT "

[[topics]]
from = 1
to = 1
topic = "HANYA ALLAH YANG BERHAK MENENTUKAN SEGALA SESUATU"

[[topics]]
from = 1
to = 1
topic = "BUKTI YANG MENGHARUSKAN KITA MEMUJI ALLAH"

[[topics]]
from = 1
to = 1
topic = "ORANG MUSYRIKIN MEMPERSEKUTUKAN ALLAH KARENA HAWA NAFSU"

[[topics]]
from = 1
to = 1
topic = "KISAH KARUN DAN KEKAYAANNYA ADALAH PELAJARAN BAGI MANUSIA"

[[topics]]
from = 1
to = 1
topic = "SATU KEBAJIKAN DIBALAS BERLIPAT GANDA"

[[topics]]
from = 1
to = 1
topic = "JANJI ALLAH AKAN MEMENANGKAN MUHAMMAD"