name = "Al-Qasas"
number = 28
[[topics]]
from = 26
to = 26
topic = "kosong"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 77
to = 77
topic = "Mengejar akhirat tidak boleh meninggalkan dunia"

[[topics]]
from = 88
to = 88
topic = "Segalanya akan binasa kecuali Allah"

