name = "Surat ALI 'IMRAAN"
number = 3

[[topics]]
from = 1
to = 1
topic = "KEESAAN DAN KEKUASAAN ALLAH "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Al Qur'an dan Kitab-kitab terdahulu"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Ancaman Allah kepada orang kafir dan pengaruh harta "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pernyataan Allah tentang keesaan dan keadilan-Nya serta agama yang diridhai-Nya"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pembalasan terhadap orang-orang yang membunuh nabi-nabi "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Orang-orang Yahudi berpaling dari hukum Allah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Bukti-bukti kekuasaan dan kebenaran Allah SWT "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Larangan berpihak kepada orang kafir"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Bukti cinta kepada Allah SWT "

[[topics]]
from = 1
to = 1
topic = "KELUARGA 'IMRAN"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Keutamaan keluarga 'Imran"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kisah Al Masih 'Isa putra Maryam "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Ajakan kepada agama Tauhid Millatu Ibrahim"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sikap Ahli Kitab terhadap orang Islam"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Keburukan-keburukan orang Yahudi"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Seorang nabi tidak akan menyuruh manusia menyembah dirinya"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Janji para Nabi kepada Allah tentang kenabian Muhammad SAW "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Juz "

[[topics]]
from = 1
to = 1
topic = "BANTAHAN ALLAH TERHADAP PENDAPAT-PENDAPAT AHLI KITAB YANG KELIRU"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Bantahan terhadap larangan orang Yahudi tentang makanan "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Bantahan terhadap pengakuan Ahli Kitab tentang rumah ibadah yang pertama"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Keharusan menjaga persatuan"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kelebihan umat Islam dari umat lain "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perumpamaan harta yang diinfakkan orang-orang kafir "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Larangan mengambil orang Yahudi sebagai teman kepercayaan"

[[topics]]
from = 1
to = 1
topic = "KISAH PERANG BADAR DAN UHUD"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sabar dan tawakkal kepada Allah pangkal kemenangan"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Larangan melakukan riba dan perintah untuk bertakwa"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perintah taat kepada Allah dan Rasul, serta sifat-sifat orang yang bertakwa "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Peringatan supaya waspada terhadap ajakan orang-orang kafir"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sebab-sebab kekalahan umat Islam dalam perang Uhud"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Menanamkan jiwa berkorban dan berjihad "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Akhlak dan beberapa sifat Nabi Muhammad SAW "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Beberapa sifat orang-orang munafik "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pahala orang-orang yang mati syahid"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Ayat-ayat yang menenteramkan hati Nabi Muhammad SAW "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kikir dan dusta serta balasannya"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Faedah selalu mengingat Allah dan merenungkan ciptaan-Nya "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kesenangan semu bagi orang kafir dan kebahagiaan abadi bagi orang mukmin"