name = "Ali-Imran"
number = 3
[[topics]]
from = 1
to = 4
topic = "Al-Qur'an & kitab-kitab sebelumnya"

[[topics]]
from = 5
to = 7
topic = "Al-Qur'an dan kitab-kitab yang sebelumnya"

[[topics]]
from = 8
to = 9
topic = "Doa petunjuk hati"

[[topics]]
from = 10
to = 13
topic = "Ancaman Allah kepada orang-orang kafir dan pengaruh harta benda duniawi"

[[topics]]
from = 14
to = 14
topic = "Kesenangan hidup di dunia"

[[topics]]
from = 15
to = 17
topic = "Doa minta ampun dari dosa"

[[topics]]
from = 18
to = 27
topic = "Pernyataan Allah tentang keesaan dan keadilan-Nya serta agama yang di ridhai-Nya"

[[topics]]
from = 28
to = 32
topic = "Larangan berpihak kepada orang kafir"

[[topics]]
from = 33
to = 37
topic = "Keutamaan keluarga 'Imran"

[[topics]]
from = 38
to = 50
topic = "Keutamaan keluarga 'Imran"

[[topics]]
from = 38
to = 50
topic = "Keutamaan keluarga 'Imran"

[[topics]]
from = 51
to = 52
topic = "Nabi Isa & sahabatnya adalah penolong agama Allah"

[[topics]]
from = 53
to = 65
topic = "Ajakan kepada agama Tauhid \"Millatu Ibrahim\""

[[topics]]
from = 66
to = 75
topic = "QS 3 Ali-Imran: 76-77"

[[topics]]
from = 78
to = 103
topic = "Bantahan Allah terhadap pendapat-pendapat ahli kitab yang keliru"

[[topics]]
from = 104
to = 104
topic = "Keharusan menjaga persatuan"

[[topics]]
from = 105
to = 127
topic = "kelebihan umat islam dari umat yang lain"

[[topics]]
from = 128
to = 129
topic = "Sabar dan tawakal kepada Allah pangkal kemenangan"

[[topics]]
from = 130
to = 135
topic = "Larangan memakan riba & ciri orang bertakwa"

[[topics]]
from = 136
to = 144
topic = "Agama Nabi Ibrahim A.S"

[[topics]]
from = 145
to = 145
topic = "Balasan dunia akhirat"

[[topics]]
from = 146
to = 151
topic = "Kehidupan dunia adalah kesenangan yang memperdaya"

[[topics]]
from = 152
to = 161
topic = "kosong"

[[topics]]
from = 162
to = 184
topic = "kosong"

[[topics]]
from = 185
to = 186
topic = "Kehidupan dunia adalah kesenangan yang memperdaya"

[[topics]]
from = 187
to = 191
topic = "Kebakhilan dan dusta serta balasannya"

[[topics]]
from = 192
to = 194
topic = "Doa orang beriman & jawaban Allah"

[[topics]]
from = 195
to = 195
topic = "Faedah selalu ingat kepada Allah dan merenungkan ciptaan-Nya"

[[topics]]
from = 196
to = 199
topic = "Kesenangan sementara bagi orang-orang kafir dan kebahagiaan abadi bagi orang mu'min"

