name = "Ar-Ruum"
number = 30
[[topics]]
from = 1
to = 20
topic = "Kebenaran pemberitaan Al-Qur'an tentang peristiwa yang akan terjadi"

[[topics]]
from = 21
to = 21
topic = "Allah menciptakan pasangan bagi manusia & kasih sayang diantaranya"

[[topics]]
from = 22
to = 36
topic = "Islam adalah agama Fitrah"

[[topics]]
from = 37
to = 40
topic = "Allah mengatur pemberian rezki dan penggunaannya"

[[topics]]
from = 41
to = 45
topic = "QS 30 Ar-Ruum: 46-60"

