name = "Ar-Ruum"
number = 30

[[topics]]
topic = "KEBENARAN PEMBERITAAN AL-QUR'AN TENTANG PERISTIWA YANG AKAN TERJADI"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Berita kemenangan bangsa Romawi, Ahli Kitab, atas bangsa Persia musyrik"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kaum yang menentang Nabi Muhammad akan hancur seperti halnya kaum yang menentang nabi-nabi terdahulu"

[[topics]]
topic = "BUKTI KEBENARAN HARI KEBANGKITAN DAN PENGGOLONGAN MANUSIA"

[[topics]]
topic = "MENJADI MUKMIN DAN KAFIR "

[[topics]]
topic = "BUKTI-BUKTI KEBESARAN ALLAH SWT YANG TERDAPAT PADA ALAM"

[[topics]]
topic = "SEMESTA"

[[topics]]
topic = "ISLAM ADALAH AGAMA FITRAH"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Suatu tamsil yang terdapat pada keadaan manusia tentang keesaan Allah "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Manusia, menurut fitrahnya, beragama tauhid "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sifat-sifat manusia yang tercela"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Allah mengatur pemberian dan penggunaan rezeki"

[[topics]]
topic = "AKIBAT YANG BURUK DAN YANG BAIK DARI PERBUATAN MANUSIA"

[[topics]]
topic = "MEMPERHATIKAN ALAM MENAMBAH KEYAKINAN TERHADAP ALLAH "

[[topics]]
topic = "BUKTI-BUKTI TENTANG KEKUASAAN ALLAH DAN KEADAAN MANUSIA"

[[topics]]
topic = "PADA HARI KIAMAT "

[[topics]]
topic = "ANJURAN MEMPERHATIKAN PERUMPAMAAN YANG TERDAPAT DALAM AL-QUR'AN"
