name = "Luqmaan"
number = 31
[[topics]]
from = 1
to = 5
topic = "Al-Qur'an sebagai petunjuk & rahmat bagi orang yang berbuat baik"

[[topics]]
from = 6
to = 11
topic = "Bukti-bukti keesaan Allah. Alam langit dipelihara dari gangguan syaitan"

[[topics]]
from = 12
to = 19
topic = "Nasihat orangtua kepada anaknya"

[[topics]]
from = 20
to = 34
topic = "Kekuasaan Allah adalah mutlak dan akibat pengingkaran terhadapnya"

