name = "Luqmaan"
number = 31

[[topics]]
from = 1
to = 11
topic = "AL-QUR'AN MENJAMIN KESUKSESAN ORANG-ORANG YANG BERIMAN "

[[topics]]
from = 12
to = 19
topic = "NASIHAT LUQMAN KEPADA ANAKNYA"

[[topics]]
from = 20
to = 34
topic = "KEKUASAAN ALLAH ADALAH MUTLAK DAN AKIBAT PENGINGKARAN TERHADAPNYA "