name = "Luqmaan"
number = 31

[[topics]]
topic = "AL-QUR'AN MENJAMIN KESUKSESAN ORANG-ORANG YANG BERIMAN "

[[topics]]
topic = "NASIHAT LUQMAN KEPADA ANAKNYA"

[[topics]]
topic = "KEKUASAAN ALLAH ADALAH MUTLAK DAN AKIBAT PENGINGKARAN TERHADAPNYA "