name = "As-Sajdah"
number = 32
[[topics]]
from = 1
to = 11
topic = "Al-Qur'an bukanlah ciptaan Muhammad S.A.W"

[[topics]]
from = 12
to = 15
topic = "Sebuah perbandingan antara orang mu'min dengan orang kafir"

[[topics]]
from = 16
to = 22
topic = "Sebuah perbandingan antara orang mu'min dengan orang kafir"

[[topics]]
from = 23
to = 30
topic = "Jangan ragu dalam menerima Al-Qur'an"

