name = "As-Sajdah"
number = 32

[[topics]]
topic = "AL-QUR'AN ADALAH WAHYU DARI ALLAH"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Al-Qur'an bukanlah ciptaan Muhammad "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Masa terciptanya alam semesta"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Proses kejadian manusia dan kebangkitannya pada hari kiamat "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sebuah perbandingan antara orang mukmin dan orang kafir"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perintah Allah untuk menerima Al-Qur'an tanpa ragu-ragu"
