name = "Al-Ahzab"
number = 33

[[topics]]
from = 1
to = 1
topic = "HUKUM KEKELUARGAAN HARUS BERDASARKAN KETETAPAN ALLAH DAN RASUL"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Takwa dan tawakkal kepada Allah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Hukum zhihar dan kedudukan anak angkat"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kedudukan hubungan darah dalam hubungan waris "

[[topics]]
from = 1
to = 1
topic = "BANTUAN ALLAH KEPADA KAUM MUSLIMIN DALAM PERANG AHZAB"

[[topics]]
from = 1
to = 1
topic = "PERANG DENGAN BANI QURAIZHAH "

[[topics]]
from = 1
to = 1
topic = "KETENTUAN ALLAH TERHADAP ISTRI NABI"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Juz "

[[topics]]
from = 1
to = 1
topic = "SIFAT-SIFAT ORANG MUKMIN DAN KEWAJIBAN MEREKA TERHADAP PERINTAH RASUL"

[[topics]]
from = 1
to = 1
topic = "ANAK ANGKAT TIDAK SAMA DENGAN ANAK KANDUNG "

[[topics]]
from = 1
to = 1
topic = "KEHARUSAN MENGINGAT ALLAH"

[[topics]]
from = 1
to = 1
topic = "MUHAMMAD ADALAH RASUL YANG DIUTUS UNTUK SEGENAP UMAT MANUSIA "

[[topics]]
from = 1
to = 1
topic = "BEBERAPA KETENTUAN ISLAM TENTANG HUKUM PERKAWINAN"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perempuan yang diceraikan sebelum dicampuri tidak ada 'iddah dan harus diberi mut'ah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perempuan yang halal dinikahi oleh Rasul"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Nabi boleh memilih di antara istri-istrinya, siapa yang dipertahankannya dan siapa dilepaskannya"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Nabi tidak boleh menikah lagi setelah ayat ini diturunkan"

[[topics]]
from = 1
to = 1
topic = "ADAB DAN SOPAN SANTUN DALAM RUMAH TANGGA NABI"

[[topics]]
from = 1
to = 1
topic = "KEHARUSAN PEREMPUAN BERJILBAB, JIKA BERADA DI LUAR RUMAH"

[[topics]]
from = 1
to = 1
topic = "ANCAMAN TERHADAP ORANG MUNAFIK DAN ORANG YANG BERBUAT KERUSUHAN DI MADINAH "

[[topics]]
from = 1
to = 1
topic = "HANYA ALLAH YANG MENGETAHUI KAPAN HARI KEBANGKITAN TERJADI"

[[topics]]
from = 1
to = 1
topic = "ANCAMAN TERHADAP ORANG KAFIR"

[[topics]]
from = 1
to = 1
topic = "TAKWA KEPADA ALLAH MEMBAWA PERBAIKAN AMAL DAN AMPUNAN DOSA "

[[topics]]
from = 1
to = 1
topic = "MENERIMA TUGAS TETAPI TIDAK MELAKSANAKANNYA ADALAH KEZALIMAN "
