name = "Al-Ahzab"
number = 33
[[topics]]
from = 1
to = 10
topic = "Bantuan Allah kepada kaum muslimin dalam peperangan Ahzab"

[[topics]]
from = 11
to = 21
topic = "Bantuan Allah kepada kaum muslimin dalam peperangan Ahzab"

[[topics]]
from = 22
to = 44
topic = "Sifat-sifat orang mu'min dan kewajiban mereka terhadap perintah rasul"

[[topics]]
from = 45
to = 58
topic = "Adab dan sopan santun dalam rumah tangga Nabi S.A.W."

[[topics]]
from = 59
to = 59
topic = "Menutup aurat / Hijab"

[[topics]]
from = 60
to = 63
topic = "Ancaman-ancaman terhadap orang-orang munafik dan orang-orang yang membuat kerusuhan di Madinah"

