name = "Saba'"
number = 34

[[topics]]
topic = "ALLAH SANGAT TERPUJI DAN ILMUNYA SANGAT SEMPURNA"

[[topics]]
topic = "KEPANDAIAN YANG DIBERIKAN KEPADA NABI DAWUD DAN KEKUASAAN"

[[topics]]
topic = "YANG DIBERIKAN KEPADA NABI SULAIMAN"

[[topics]]
topic = "KEINGKARAN KAUM SABA' TERHADAP NIKMAT ALLAH DAN AKIBATNYA"

[[topics]]
topic = "SEMBAHAN SELAIN ALLAH TIDAK MEMPUNYAI KEKUASAAN SEDIKIT PUN "

[[topics]]
topic = "RISALAH MUHAMMAD ADALAH UNIVERSAL"

[[topics]]
topic = "KEINGKARAN ORANG KAFIR DAN KEADAAN MEREKA DI AKHIRAT"

[[topics]]
topic = "PERNYATAAN ALLAH TENTANG MUHAMMAD DAN TUGASNYA"