name = "Fatir"
number = 35
[[topics]]
from = 1
to = 7
topic = "Allah adalah Pencipta, Penguasa, dan Pemberi rahmat"

[[topics]]
from = 29
to = 29
topic = "Balasan kepada orang yang membaca Al-Qur'an, mendirikan sholat & sedekah"

[[topics]]
from = 0
to = 0
topic = "kosong"

