name = "Ash-Shaaffaat"
number = 37
[[topics]]
from = 1
to = 70
topic = "Bukti-bukti keesaan Allah. Alam langit dipelihara dari gangguan syaitan"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 100
to = 101
topic = "Doa memohon anak yang soleh"

[[topics]]
from = 0
to = 0
topic = "kosong"

