name = "Az-Zumar"
number = 39
[[topics]]
from = 1
to = 5
topic = "Beribadah kepada Allah dengan hati yang penuh keikhlasan"

[[topics]]
from = 10
to = 18
topic = "Beribadah kepada Allah dengan hati yang penuh keikhlasan"

[[topics]]
from = 53
to = 55
topic = "Allah mengampuni semua dosa"

