name = "An-Nisaa"
number = 4
[[topics]]
from = 1
to = 1
topic = "Allah menciptakan pasangan bagi manusia"

[[topics]]
from = 2
to = 6
topic = "Kewajiban para wasi terhadap asuhannya dan kewajiban para wali terhadap orang yang dibawah perwalian"

[[topics]]
from = 7
to = 11
topic = "Hukum waris"

[[topics]]
from = 12
to = 14
topic = "Hukum waris"

[[topics]]
from = 15
to = 16
topic = "kosong"

[[topics]]
from = 17
to = 18
topic = "Taubat"

[[topics]]
from = 19
to = 28
topic = "Beberapa hukum perkawinan"

[[topics]]
from = 15
to = 16
topic = "kosong"

[[topics]]
from = 34
to = 35
topic = "Manajemen rumah tangga"

[[topics]]
from = 36
to = 36
topic = "Kewajiban terhadap Allah dan terhadap sesama manusia"

[[topics]]
from = 37
to = 96
topic = "kosong"

[[topics]]
from = 97
to = 100
topic = "Kewajiban berhijrah di jalan Allah dan balasannya"

[[topics]]
from = 101
to = 122
topic = "kosong"

[[topics]]
from = 123
to = 126
topic = "Balasan dari Perbuatan, & ikhlas berserah diri"

[[topics]]
from = 127
to = 146
topic = "kosong"

[[topics]]
from = 147
to = 152
topic = "Larangan melontarkan ucapan-ucapan buruk kepada seseorang"

[[topics]]
from = 147
to = 152
topic = "kosong"

[[topics]]
from = 153
to = 176
topic = "kosong"

