name = "AL-MU'MIN / Ghafir"
number = 40

[[topics]]
topic = "PENENTANGAN TERHADAP AGAMA PASTI MENEMUI KEGAGALAN"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Orang-orang mukmin jangan teperdaya oleh kemakmuran orang-orang musyrikin"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Para malaikat bertasbih kepada Allah dan mendoakan orang-orang mukmin "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Keinginan orang-orang kafir keluar dari neraka"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kewajiban menunaikan ibadah kepada Allah "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pelajaran yang dapat diambil dari kisah Nabi Musa "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pengingkaran terhadap kekuasaan Allah hanyalah karena kesombongan semata "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Allah akan memperkenankan doa hamba-Nya"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kekuasaan Allah yang tercermin pada alam semesta "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Nasib orang yang menentang ayat-ayat Allah dan rasul-Nya "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Rasul ada yang disebutkan kisahnya dalam Al-Qur'an dan ada yang tidak disebutkan "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pelajaran yang dapat diambil dari peristiwa yang terjadi pada umat-umat terdahulu "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Iman pada waktu azab telah datang tidak berguna lagi "
