name = "Gafir"
number = 40
[[topics]]
from = 1
to = 20
topic = "Orang-orang mu'min janganlah terpedaya oleh kemakmuran orang-orang musyrikin"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 60
to = 60
topic = "Tentang doa"

[[topics]]
from = 61
to = 65
topic = "Allah akan memperkenankan do'a hamba-Nya"

