name = "Fussilat"
number = 41
[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 30
to = 35
topic = "Sifat baik dianugerahkan kepada orang yang sabar"

[[topics]]
from = 0
to = 0
topic = "kosong"

