name = "Fussilat"
number = 41

[[topics]]
from = 1
to = 1
topic = "NABI ADALAH MANUSIA BIASA YANG DIBERI WAHYU"

[[topics]]
from = 1
to = 1
topic = "ALLAH MENCIPTAKAN LANGIT DAN BUMI DALAM BEBERAPA PERIODE"

[[topics]]
from = 1
to = 1
topic = "PERINGATAN KEPADA KAUM QURAISY TENTANG PERISTIWA YANG DIALAMI KAUM 'AD DAN TSAMUD"

[[topics]]
from = 1
to = 1
topic = "ANGGOTA TUBUH MANUSIA AKAN MENJADI SAKSI PADA HARI KIAMAT"

[[topics]]
from = 1
to = 1
topic = "PEMBALASAN ALLAH TERHADAP ORANG KAFIR DAN ORANG YANG BERIMAN "

[[topics]]
from = 1
to = 1
topic = "AL-QUR'AN ADALAH PETUNJUK DAN PENAWAR "
