name = "Asy-Syuraa"
number = 42
[[topics]]
from = 1
to = 12
topic = "Perselisihan-perselisihan umat manusia dikembalikan penyelesainnya kepada Kitab Allah"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 30
to = 43
topic = "Bersabar & Memaafkan"

[[topics]]
from = 0
to = 0
topic = "kosong"

