name = "Az-Zukhruf"
number = 43

[[topics]]
topic = "KAUM MUSYRIKIN MENGAKUI BAHWA ALLAH-LAH PENCIPTA LANGIT DAN"

[[topics]]
topic = "BUMI MESKIPUN MEREKA MENYEMBAH BERHALA "

[[topics]]
topic = "KEINGKARAN KAUM MUSYRIKIN KARENA BERPEGANG TEGUH PADA TRADISI "

[[topics]]
topic = "NABI IBRAHIM SEBAGAI NENEK MOYANG MEREKA SENDIRI MENENTANG TRADISI"

[[topics]]
topic = "KEKAYAAN DAN PERHIASAN HANYALAH KENIKMATAN HIDUP DUNIAWI SEDANGKAN KEBAHAGIAAN DI AKHIRAT HANYA DAPAT DICAPAI DENGAN TAKWA "

[[topics]]
topic = "KEHANCURAN FIR'AUN ADALAH PELAJARAN BAGI UMAT ISLAM"

[[topics]]
topic = "NABI 'ISA MENGAJAK KAUMNYA UNTUK BERIMAN KEPADA ALLAH "

[[topics]]
topic = "KEBAHAGIAAN PENDUDUK SURGA DAN KESENGSARAAN PENDUDUK NERAKA"

[[topics]]
topic = "BANTAHAN AL-QUR'AN TENTANG KEPERCAYAAN TUHAN MEMPUNYAI ANAK "

