name = "Ad-Dhukhan"
number = 44

[[topics]]
from = 1
to = 1
topic = "KAUM MUSYRIKIN DIAZAB ALLAH DENGAN KELAPARAN SEBAGAI HUKUMAN YANG RINGAN"

[[topics]]
from = 1
to = 1
topic = "KAUM MUSYRIKIN TETAP INGKAR, ALLAH MENDATANGKAN AZAB YANG BESAR"

[[topics]]
from = 1
to = 1
topic = "KISAH MUSA DAN FIR'AUN SEBAGAI PELAJARAN BAGI ORANG KAFIR"

[[topics]]
from = 1
to = 1
topic = "PERBUATAN JELEK DAN AMAL SALEH AKAN MENDAPATKAN BALASAN YANG SETIMPAL"

