name = "Al-Ahqaaf"
number = 46
[[topics]]
from = 1
to = 14
topic = "Kebenaran tauhid dan kebatilan syirik"

[[topics]]
from = 15
to = 15
topic = "Doa mohon dapat bersyukur"

[[topics]]
from = 16
to = 35
topic = "Kebenaran tauhid dan kebatilan syirik"

