name = "Al-Ahqaaf"
number = 46

[[topics]]
from = 1
to = 1
topic = "KEBENARAN TAUHID DAN KEBATILAN SYIRIK"

[[topics]]
from = 1
to = 1
topic = "KEWAJIBAN MENGHORMATI KEDUA ORANG TUA "

[[topics]]
from = 1
to = 1
topic = "KEHANCURAN KAUM 'AD "

[[topics]]
from = 1
to = 1
topic = "PENYIARAN AL-QUR'AN KEPADA GOLONGAN JIN "
