name = "Muhammad"
number = 47
[[topics]]
from = 1
to = 6
topic = "Sikap menghadapi orang-orang kafir dalam peperangan"

[[topics]]
from = 7
to = 9
topic = "Sikap menghadapi orang-orang kafir dalam peperangan"

[[topics]]
from = 10
to = 38
topic = "Ancaman terhadp orang-orang munafik dan orang-orang murtad"

