name = "Muhammad"
number = 47

[[topics]]
topic = "KETENTUAN-KETENTUAN PEPERANGAN DALAM ISLAM"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sikap menghadapi orang-orang kafir dalam peperangan "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Orang mukmin pasti menang dan orang kafir pasti hancur"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Ancaman terhadap orang munafik dan orang murtad"
