name = "Muhammad"
number = 47

[[topics]]
from = 1
to = 38
topic = "KETENTUAN-KETENTUAN PEPERANGAN DALAM ISLAM"
    [[topics.subs]]
    from = 1
    to = 6
    text = "Sikap menghadapi orang-orang kafir dalam peperangan "
    [[topics.subs]]
    from = 7
    to = 19
    text = "Orang mukmin pasti menang dan orang kafir pasti hancur"
    [[topics.subs]]
    from = 20
    to = 38
    text = "Ancaman terhadap orang munafik dan orang murtad"
