name = "Al-Fath"
number = 48
[[topics]]
from = 1
to = 7
topic = "Kabar gembira kepada Nabi Muhammad S.A.W dan kaum muslimin"

[[topics]]
from = 8
to = 17
topic = "Kabar gembira kepada Nabi Muhammad S.A.W dan kaum muslimin"

[[topics]]
from = 18
to = 26
topic = "kosong"

[[topics]]
from = 27
to = 29
topic = "Kebenaran mimpi Nabi Muhammad memasuki Mekah terbukti"

