name = "Al-Fath"
number = 48

[[topics]]
from = 1
to = 1
topic = "PERDAMAIAN HUDAIBIYAH ADALAH KEMENANGAN YANG BESAR BAGI KAUM MUSLIMIN"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kabar gembira bagi Nabi Muhammad dan kaum muslimin"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Terjadinya Bai'aturridhwan"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Celaan untuk orang yang takut berperang "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Allah meridhai orang-orang yang melakukan Bai'aturridhwan dan menjanjikan kemenangan bagi kaum muslimin"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Mimpi Nabi Muhammad memasuki Mekah akan terbukti"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sifat-sifat Nabi Muhammad SAW dan Sahabatnya di dalam Taurat dan Injil "