name = "Al-Fath"
number = 48

[[topics]]
from = 1
to = 29
topic = "PERDAMAIAN HUDAIBIYAH ADALAH KEMENANGAN YANG BESAR BAGI KAUM MUSLIMIN"
    [[topics.subs]]
    from = 1
    to = 7
    text = "Kabar gembira bagi Nabi Muhammad dan kaum muslimin"
    [[topics.subs]]
    from = 8
    to = 10
    text = "Terjadinya Bai'aturridhwan"
    [[topics.subs]]
    from = 11
    to = 17
    text = "Celaan untuk orang yang takut berperang "
    [[topics.subs]]
    from = 18
    to = 26
    text = "Allah meridhai orang-orang yang melakukan Bai'aturridhwan dan menjanjikan kemenangan bagi kaum muslimin"
    [[topics.subs]]
    from = 27
    to = 28
    text = "Mimpi Nabi Muhammad memasuki Mekah akan terbukti"
    [[topics.subs]]
    from = 29
    to = 29
    text = "Sifat-sifat Nabi Muhammad SAW dan Sahabatnya di dalam Taurat dan Injil "