name = "Al-Hujuraat"
number = 49
[[topics]]
from = 1
to = 5
topic = "Tatakrama terhadap Rasulullah S.A.W"

[[topics]]
from = 6
to = 6
topic = "Perintah memastikan kebenaran sebuah berita"

[[topics]]
from = 7
to = 9
topic = "Tatakrama terhadap Rasulullah S.A.W"

[[topics]]
from = 10
to = 12
topic = "Orang muslim itu bersaudara & Jangan merendahkan orang lain / berprasangka"

[[topics]]
from = 13
to = 13
topic = "Manusia diciptakan berbeda untuk saling mengenal"

[[topics]]
from = 14
to = 18
topic = "Ciri-ciri iman yang sebenarnya"

