name = "Al-Hujuraat"
number = 49

[[topics]]
from = 1
to = 1
topic = "TATA KRAMA TERHADAP RASULULLAH"

[[topics]]
from = 1
to = 1
topic = "PERATURAN TENTANG PERGAULAN UMAT ISLAM"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Cara menghadapi berita yang dibawa orang fasik"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Cara menyelesaikan persengketaan yang timbul antara kaum Muslimin "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Larangan memperolok-olokkan, banyak berprasangka, dan lain-lain "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Manusia diciptakan berbangsa-bangsa untuk saling mengenal"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Ciri-ciri iman yang sebenarnya"