name = "Al-Maidah"
number = 5
[[topics]]
from = 6
to = 6
topic = "Perintah untuk wudhu & membersihkan badan"

[[topics]]
from = 8
to = 8
topic = "Kewajiban berlaku Adil dan Jujur"

[[topics]]
from = 9
to = 31
topic = "kosong"

[[topics]]
from = 32
to = 40
topic = "Hukum terhadap perusuh dan pengacau keamanan"

[[topics]]
from = 51
to = 53
topic = "Dilarang berteman akrab dengan orang-orang Yahudi dan Nasrani dan akibat melanggarnya"

[[topics]]
from = 89
to = 93
topic = "Larangan meminum khamar, berjudi, berkorban untuk berhala dan mengundi nasib"

