name = "Al-Maidah"
number = 5

[[topics]]
from = 1
to = 1
topic = "JANJI PRASETIA KEPADA ALLAH DAN PENYEMPURNAAN AGAMA ISLAM"

[[topics]]
from = 1
to = 1
topic = "WUDHU, MANDI, DAN TAYAMUM "

[[topics]]
from = 1
to = 1
topic = "KEWAJIBAN BERSIKAP ADIL DAN JUJUR"

[[topics]]
from = 1
to = 1
topic = "PENGINGKARAN JANJI PRASETIA OLEH ORANG YAHUDI DAN NASRANI "

[[topics]]
from = 1
to = 1
topic = "KEENGGANAN BANGSA YAHUDI MENAATI PERINTAH NABI MUSA A.S. UNTUK MEMASUKI PALESTINA DAN AKIBATNYA "

[[topics]]
from = 1
to = 1
topic = "KISAH PEMBUNUHAN PERTAMA DAN BESARNYA MALAPETAKA AKIBAT PEMBUNUHAN"

[[topics]]
from = 1
to = 1
topic = "HUKUMAN BAGI PERUSUH DAN PENGACAU KEAMANAN"

[[topics]]
from = 1
to = 1
topic = "PENGINGKARAN ORANG YAHUDI TERHADAP HUKUM-HUKUM TAURAT"

[[topics]]
from = 1
to = 1
topic = "DAN KEWAJIBAN MEMUTUSKAN PERKARA MENURUT HUKUM YANG DITURUNKAN ALLAH "

[[topics]]
from = 1
to = 1
topic = "LARANGAN BERTEMAN AKRAB DENGAN ORANG YAHUDI DAN NASRANI"

[[topics]]
from = 1
to = 1
topic = "DAN AKIBAT MELANGGARNYA"

[[topics]]
from = 1
to = 1
topic = "LAKNAT ALLAH TERHADAP ORANG YAHUDI "

[[topics]]
from = 1
to = 1
topic = "KEWAJIBAN RASULULLAH SAW MENYAMPAIKAN AGAMA"

[[topics]]
from = 1
to = 1
topic = "PERNYATAAN ALLAH TENTANG KEKAFIRAN ORANG YANG MEYAKINI 'ISA A.S. SEBAGAI TUHAN "

[[topics]]
from = 1
to = 1
topic = "PENYEBAB LAKNAT ALLAH TERHADAP ORANG YAHUDI "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Juz "

[[topics]]
from = 1
to = 1
topic = "HUBUNGAN ORANG YAHUDI DAN NASRANI DENGAN ORANG MUKMIN "

[[topics]]
from = 1
to = 1
topic = "PERINGATAN UNTUK KAUM MUSLIMIN TERKAIT ADAT JAHILIYAH YANG"

[[topics]]
from = 1
to = 1
topic = "TERLARANG"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Larangan mengharamkan makanan yang halal "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sumpah dan kaffaratnya "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Larangan meminum khamar, berjudi, berkurban untuk berhala, dan mengundi nasib "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Menghormati Ka'bah sebagai pusat kehidupan manusia,"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Larangan bertanya sesuatu yang menyebabkan kemudharatan"

[[topics]]
from = 1
to = 1
topic = "ANJURAN BERWASIAT DENGAN PERSAKSIAN"

[[topics]]
from = 1
to = 1
topic = "SALAH SATU PERISTIWA PADA HARI KIAMAT"

[[topics]]
from = 1
to = 1
topic = "BEBERAPA KISAH TENTANG 'ISA A.S. "