name = "Qaaf"
number = 50
[[topics]]
from = 1
to = 15
topic = "Hari Berbangkit"

[[topics]]
from = 16
to = 16
topic = "Allah itu dekat"

[[topics]]
from = 17
to = 26
topic = "Kejadian-kejadian dalam alam membuktikan kebenaran adanya hari berbangkit"

[[topics]]
from = 0
to = 0
topic = "kosong"

