name = "Qaaf"
number = 50

[[topics]]
from = 1
to = 1
topic = "HARI KEBANGKITAN "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pengingkaran kaum musyrikin terhadap kenabian Muhammad dan hari kebangkitan "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kejadian-kejadian alam membuktikan kebenaran adanya hari kebangkitan"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pelajaran yang dapat diambil dari umat-umat terdahulu yang menentang para nabi"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Gerak-gerik dan perkataan manusia dicatat oleh para malaikat "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Balasan terhadap amal baik dan perbuatan jelek"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Ancaman terhadap orang yang mengingkari hari kebangkitan"