name = "Ath-Thuur"
number = 52
[[topics]]
from = 1
to = 20
topic = "Bukit"

[[topics]]
from = 21
to = 21
topic = "Allah mempertemukan keluarga yang beriman dengan anak cucu mereka di dalam surga"

[[topics]]
from = 22
to = 49
topic = "Bukit"

