name = "Ath-Thur"
number = 52

[[topics]]
from = 1
to = 1
topic = "SUMPAH YANG MENEGASKAN BAHWA AZAB ALLAH PASTI MENIMPA ORANG"

[[topics]]
from = 1
to = 1
topic = "YANG MENDUSTAKAN DAN KARUNIANYA PASTI DILIMPAHKAN KEPADA ORANG YANG BERTAKWA "

[[topics]]
from = 1
to = 1
topic = "BANTAHAN ALLAH TERHADAP OCEHAN KAUM MUSYRIKIN"

[[topics]]
from = 1
to = 1
topic = "KEHARUSAN BERSABAR, BERTASBIH, DAN SHALAT MALAM"