name = "Ath-Thur"
number = 52

[[topics]]
from = 1
to = 28
topic = "SUMPAH YANG MENEGASKAN BAHWA AZAB ALLAH PASTI MENIMPA ORANG YANG MENDUSTAKAN DAN KARUNIANYA PASTI DILIMPAHKAN KEPADA ORANG YANG BERTAKWA"

[[topics]]
from = 29
to = 47
topic = "BANTAHAN ALLAH TERHADAP OCEHAN KAUM MUSYRIKIN"

[[topics]]
from = 48
to = 49
topic = "KEHARUSAN BERSABAR, BERTASBIH, DAN SHALAT MALAM"