name = "An-Najm"
number = 53

[[topics]]
topic = "ALLAH BERSUMPAH BAHWA WAHYU YANG DITURUNKAN KEPADA NABI MUHAMMAD ADALAH BENAR "

[[topics]]
topic = "CELAAN ALLAH KEPADA KAUM MUSYRIKIN YANG MENGHARAPKAN SYAF'AT DARI MALAIKAT"

[[topics]]
topic = "ORANG YANG MENJAUHI DOSA BESAR MENDAPAT AMPUNAN DAN BALASAN YANG BAIK"

[[topics]]
topic = "KEHANCURAN ORANG YANG MENDUSTAKAN KEBENARAN DAN PERTANGGUNGJAWABAN MANUSIA ATAS PERBUATANNYA"
