name = "Al-Qamar"
number = 54
[[topics]]
from = 17
to = 17
topic = "kosong"

[[topics]]
from = 17
to = 17
topic = "Al-Qur'an sebagai peringatan & pelajaran"

[[topics]]
from = 22
to = 22
topic = "Al-Qur'an sebagai peringatan & pelajaran"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 40
to = 40
topic = "Al-Qur'an sebagai peringatan & pelajaran"

[[topics]]
from = 0
to = 0
topic = "kosong"

