name = "Al-Qamar"
number = 54

[[topics]]
topic = "MUSUH NABI MUHAMMAD AKAN MENGALAMI KEHANCURAN SEBAGAIMANA MUSUH RASUL TERDAHULU"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Berita kehancuran musuh Nabi Muhammad"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kehancuran kaum Nabi Nuh"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kehancuran kaum 'Ad"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kehancuran kaum Tsamud"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kehancuran kaum Luth"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kehancuran Fir'aun"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Peringatan kepada kaum musyrikin bahwa mereka tidak lebih kuat dari umat-umat yang telah dihancurkan Allah "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Balasan terhadap orang yang berdosa dan pahala bagi orang yang bertakwa"
