name = "Ar-Rahmaan"
number = 55

[[topics]]
topic = "BEBERAPA NIKMAT ALLAH YANG DAPAT DIRASAKAN DI DUNIA "

[[topics]]
topic = "ANCAMAN ALLAH TERHADAP PERBUATAN DURHAKA"

[[topics]]
topic = "PAHALA BAGI ORANG YANG BERTAKWA"

