name = "Al-Hadid"
number = 57

[[topics]]
topic = "SEGALA SESUATU PADA HAKIKATNYA MILIK ALLAH MAKA JANGANLAH KAMU MERASA BERAT MENGINFAKKAN HARTA"

[[topics]]
topic = "BESI ADALAH KARUNIA ALLAH YANG MERUPAKAN POKOK KEKUATAN UNTUK MEMBELA AGAMA ALLAH DAN MEMENUHI KEPERLUAN HIDUP"

[[topics]]
topic = "TIDAK ADA KERAHIBAN DALAM AGAMA ISLAM"
