name = "Al-Hadid"
number = 57

[[topics]]
from = 1
to = 24
topic = "SEGALA SESUATU PADA HAKIKATNYA MILIK ALLAH MAKA JANGANLAH KAMU MERASA BERAT MENGINFAKKAN HARTA"

[[topics]]
from = 25
to = 26
topic = "BESI ADALAH KARUNIA ALLAH YANG MERUPAKAN POKOK KEKUATAN UNTUK MEMBELA AGAMA ALLAH DAN MEMENUHI KEPERLUAN HIDUP"

[[topics]]
from = 27
to = 29
topic = "TIDAK ADA KERAHIBAN DALAM AGAMA ISLAM"
