name = "Al-Mujaadalah"
number = 58

[[topics]]
topic = "BEBERAPA KETENTUAN DALAM ISLAM "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Hukum Zhihar"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Celaan terhadap perundingan rahasia untuk memusuhi Islam"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sopan-santun menghadiri majelis Nabi"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Larangan bersahabat dengan orang yang memusuhi Islam"