name = "Al-Mujaadalah"
number = 58

[[topics]]
from = 1
to = 22
topic = "BEBERAPA KETENTUAN DALAM ISLAM "
    [[topics.subs]]
    from = 1
    to = 6
    text = "Hukum Zhihar"
    [[topics.subs]]
    from = 7
    to = 10
    text = "Celaan terhadap perundingan rahasia untuk memusuhi Islam"
    [[topics.subs]]
    from = 11
    to = 13
    text = "Sopan-santun menghadiri majelis Nabi"
    [[topics.subs]]
    from = 14
    to = 22
    text = "Larangan bersahabat dengan orang yang memusuhi Islam"