name = "Al Hasyr"
number = 59

[[topics]]
from = 1
to = 1
topic = "PENGUSIRAN ORANG-ORANG YAHUDI DARI MADINAH"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pengusiran Bani Nadhir dari Madinah "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Hukum Fai "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Orang munafik tidak menepati janji terhadap orang Yahudi "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Beberapa peringatan"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Beberapa Al-Asmaa' al Husna "