name = "Al-An'am"
number = 6
[[topics]]
from = 1
to = 20
topic = "Keagungan Allah dan persaksian-Nya atas kenabian Muhammad S.A.W."

[[topics]]
from = 32
to = 32
topic = "Perbedaan dunia & akhirat"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 53
to = 58
topic = "Tuntunan-tuntunan dalam menghadapi masyarakat"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 106
to = 108
topic = "Saling menghormati dalam beragama"

[[topics]]
from = 141
to = 143
topic = "Besarnya Karunia Allah kepada Manusia"

[[topics]]
from = 159
to = 161
topic = "Peraturan-peraturan yang dibuat-buat oleh kaum musyrikin dan pimpinan Allah terhadap kaum muslimin"

