name = "Al-Jumu'ah"
number = 62

[[topics]]
topic = "PENGUTUSAN MUHAMMAD ADALAH KARUNIA ALLAH KEPADA MANUSIA "

[[topics]]
topic = "PERINGATAN KEPADA UMAT ISLAM SUPAYA JANGAN SEPERTI ORANG YAHUDI YANG TIDAK MENGAMALKAN ISI KITAB SUCI "

[[topics]]
topic = "BEBERAPA HUKUM YANG BERHUBUNGAN DENGAN SHALAT JUM'AT"
