name = "Al-Munafiquun"
number = 63

[[topics]]
from = 1
to = 1
topic = "ORANG-ORANG MUNAFIK"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sifat-sifat orang munafik"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Peringatan kepada orang-orang mukmin"