name = "At-Taghabun"
number = 64
[[topics]]
from = 1
to = 10
topic = "Kesalahan-kesalahan manusia akan dinampakkan Allah pada hari kiamat"

[[topics]]
from = 11
to = 13
topic = "Kesalahan-kesalahan manusia akan dinampakkan pada hari kiamat"

[[topics]]
from = 14
to = 18
topic = "QS 65 At-Talaq: 1-12"

