name = "At-Taghabun"
number = 64

[[topics]]
from = 1
to = 1
topic = "KESALAHAN MANUSIA AKAN DITAMPAKKAN ALLAH PADA HARI KIAMAT"

[[topics]]
from = 1
to = 1
topic = "BERHATI-HATI TERHADAP KEHIDUPAN DUNIA "