name = "At-Tahriim"
number = 66
[[topics]]
from = 1
to = 5
topic = "Beberapa tuntunan tentang kehidupan rumah tangga"

[[topics]]
from = 6
to = 9
topic = "Perintah memelihara diri dan keluarga dari adzab Allah & perintah taubat dan berjihad"

[[topics]]
from = 10
to = 12
topic = "Contoh-contoh tentang isteri yang tidak baik dan isteri yang baik"

