name = "At-Tahrim"
number = 66

[[topics]]
topic = "BEBERAPA TUNTUNAN TENTANG KEHIDUPAN RUMAH TANGGA "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Nabi Muhammad dan istri-istrinya"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perintah taubat dan berjihad "

[[topics]]
topic = "CONTOH ISTRI YANG TIDAK BAIK DAN ISTRI YANG BAIK"