name = "Al-Haqqah"
number = 69

[[topics]]
from = 1
to = 1
topic = "KEPASTIAN HARI KIAMAT "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Orang yang mendustakan kebenaran pasti binasa "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Peristiwa-peristiwa ketika hari kiamat terjadi"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Hari penghisaban dan peristiwa-peristiwa berikutnya"

[[topics]]
from = 1
to = 1
topic = "AL-QUR'AN BENAR-BENAR WAHYU ALLAH "
