name = "Al-A'Raf"
number = 7

[[topics]]
topic = "KEWAJIBAN MENGIKUTI WAHYU DAN AKIBAT MENANTANGNYA"

[[topics]]
topic = "PERMUSUHAN DAN GODAAN SETAN TERHADAP MANUSIA"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Penghargaan Allah kepada Nabi Adam dan keturunannya "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Peringatan Allah terhadap godaan setan"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Adab berpakaian, makan, dan minum"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pengutusan para rasul dan akibat penerimaan dan penolakan kerasulan "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Siapakah Tuhan semesta alam dan bagaimana bermohon kepada-Nya?"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Bukti kekuasaan Allah membangkitkan manusia setelah mati"

[[topics]]
topic = "KISAH BEBERAPA ORANG RASUL "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kisah Nabi Nuh A.S.  "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kisah Nabi Huud A.S. "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kisah Nabi Shaleh A.S. "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kisah Nabi Luth A.S.  "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kisah Nabi Syu'aib A.S. "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Juz "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kisah Nabi Musa A.S.  "

[[topics]]
topic = "PENGKHIANATAN ORANG-ORANG YAHUDI TERHADAP PERJANJIAN DENGAN ALLAH"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Ketauhidan sesuai dengan fitrah manusia"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Perumpamaan orang-orang yang mendustakan ayat-ayat Allah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sifat-sifat penghuni neraka"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kedatangan azab Allah kepada orang-orang yang mendustakan ayat-ayat-Nya dengan cara istidraj"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Hanya Allah yang mengetahui waktu hari kiamat"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Tuhan mengingatkan manusia kepada asal-usul kejadiannya "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Berhala tidak pantas disembah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Dasar-dasar al-akhlaqul kariimah "

[[topics]]
topic = "ADAB MENDENGAR AL-QUR'AN DAN BERZIKIR "