name = "Al-A'Raaf"
number = 7
[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 23
to = 24
topic = "Doa mohon ampunan & rahmat"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 35
to = 35
topic = "Rasul dari kalanganmu sendiri"

[[topics]]
from = 54
to = 55
topic = "Penciptaan semesta & cara berdoa"

[[topics]]
from = 54
to = 55
topic = "kosong"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 85
to = 87
topic = "Kisah Nabi Syu'aib A.S"

[[topics]]
from = 174
to = 188
topic = "Penghianatan orang-orang Yahudi terhadap perjanjian manusia dengan Allah"

[[topics]]
from = 204
to = 204
topic = "Perintah mendengar bacaan Qur'an"

[[topics]]
from = 0
to = 0
topic = "kosong"

