name = "Al-Ma'aarij"
number = 70

[[topics]]
from = 1
to = 1
topic = "KEPASTIAN DATANGNYA AZAB KEPADA ORANG KAFIR"

[[topics]]
from = 1
to = 1
topic = "AJARAN ISLAM UNTUK MENGATASI SIFAT-SIFAT YANG JELEK PADA MANUSIA"

[[topics]]
from = 1
to = 1
topic = "AZAB YANG MENGHINAKAN AKAN MENIMPA ORANG YANG MENDUSTAKAN ALLAH"
