name = "Al-Jinn"
number = 72

[[topics]]
from = 1
to = 1
topic = "JIN MASUK ISLAM SETELAH MENDENGAR AL-QUR'AN"

[[topics]]
from = 1
to = 1
topic = "PEMELIHARAAN ALLAH TERHADAP WAHYU YANG DITURUNKAN KEPADA NABI"
