name = "Al-Muzzammil"
number = 73

[[topics]]
from = 1
to = 19
topic = "PETUNJUK ALLAH KEPADA NABI MUHAMMAD UNTUK MEMPERSIAPKAN DIRI DALAM BERDAKWAH"
    [[topics.subs]]
    from = 1
    to = 9
    text = "Kewajiban shalat malam atas Nabi Muhammad"
    [[topics.subs]]
    from = 10
    to = 19
    text = "Beberapa petunjuk lainnya untuk Nabi Muhammad "

[[topics]]
from = 20
to = 20
topic = "BEBERAPA PETUNJUK BAGI KAUM MUSLIMIN"
