name = "Al-Muzzammil"
number = 73

[[topics]]
from = 1
to = 1
topic = "PETUNJUK ALLAH KEPADA NABI MUHAMMAD UNTUK MEMPERSIAPKAN"

[[topics]]
from = 1
to = 1
topic = "DIRI DALAM BERDAKWAH "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kewajiban shalat malam atas Nabi Muhammad"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Beberapa petunjuk lainnya untuk Nabi Muhammad "

[[topics]]
from = 1
to = 1
topic = "BEBERAPA PETUNJUK BAGI KAUM MUSLIMIN"
