name = "Al-Mudatsir"
number = 74

[[topics]]
topic = "PERINTAH KEPADA NABI UNTUK BERDAKWAH "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Beberapa petunjuk dalam berdakwah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Urusan orang yang ingkar kepada Allah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Yang menerima dakwah akan mendapat pahala dan yang menolaknya akan masuk neraka"
