name = "Al-Insan"
number = 76

[[topics]]
topic = "KEHIDUPAN MANUSIA MENUJU KESEMPURNAAN"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Proses kejadian manusia "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Balasan Allah kepada orang yang berbuat kebajikan dan tingkatan balasan"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Tuntunan-tuntunan Allah kepada Nabi Muhammad "
    