name = "Al-Insaan"
number = 76
[[topics]]
from = 1
to = 11
topic = "Kehidupan manusia menuju kesempurnaan"

[[topics]]
from = 12
to = 22
topic = "Kesempurnaan hidup di dalam surga"

[[topics]]
from = 23
to = 31
topic = "Tuntunan-tuntunan Allah kepada Muhammad SAW"

