name = "Al-Mursalaah"
number = 77

[[topics]]
from = 1
to = 1
topic = "KEADAAN MANUSIA PADA HARI KEPUTUSAN "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Segala ancaman Allah pasti terjadi "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Azab yang ditimpakan kepada orang yang mendustakan kebenaran dan balasan untuk orang yang bertakwa"

