name = "An-Nazi'at"
number = 79

[[topics]]
from = 1
to = 14
topic = "Penegasan Hari Kebangkitan Kepada Orang Musyrik yang Mengingkarinya"

[[topics]]
from = 15
to = 26
topic = "Kisah Nabi Musa dan Fir'aun Sebagai Penghibur Bagi Nabi Muhammad"

[[topics]]
from = 27
to = 33
topic = "Membangkitkan Manusia Adalah Mudah Bagi Allah Seperti Menciptakan Alam Semesta"

[[topics]]
from = 34
to = 46
topic = "Pada Hari Kiamat Manusia Teringat Akan Perbuatannya di Dunia"
