name = "An-Nazi'at"
number = 79

[[topics]]
from = 1
to = 1
topic = "PENEGASAN HARI KEBANGKITAN KEPADA ORANG MUSYRIK YANG MENGINGKARINYA"

[[topics]]
from = 1
to = 1
topic = "KISAH NABI MUSA DAN FIR'AUN SEBAGAI PENGHIBUR BAGI NABI MUHAMMAD"

[[topics]]
from = 1
to = 1
topic = "MEMBANGKITKAN MANUSIA ADALAH MUDAH BAGI ALLAH SEPERTI MENCIPTAKAN ALAM SEMESTA "

[[topics]]
from = 1
to = 1
topic = "PADA HARI KIAMAT MANUSIA TERINGAT AKAN PERBUATANNYA DI DUNIA "