name = "Al-Anfaal"
number = 8

[[topics]]
from = 1
to = 1
topic = "KISAH PERANG BADAR "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Cara pembagian ghanimah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Sifat-sifat orang mukmin"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Keengganan sebagian sahabat untuk pergi ke perang Badar dan pertolongan Allah kepada kaum muslimin"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Larangan melarikan diri dari pertempuran"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Larangan menyalahi perintah-perintah Allah "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kewajiban mentaati perintah Allah dan Rasul-Nya"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Larangan berkhianat dan faedah bertakwa"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Permusuhan kaum musyrikin terhadap Nabi dan kewajiban memerangi mereka sampai agama"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Allah tegak"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Juz "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Cara pembagian ghanimah"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Rahmat Allah kepada kaum Muslimin dalam perang Badar "
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kewajiban berteguh hati, bersatu dalam peperangan, dan larangan berlaku sombong dan riya'"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Pengkhianatan setan terhadap janjinya kepada pengikut-pengikutnya"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Kebinasaan sesuatu kaum disebabkan perbuatan mereka sendiri"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Syirik adalah dosa yang paling besar dan sikap menghadapi kaum musyrikin dalam peperangan"
    [[topics.subs]]
    from = 1
    to = 1
    text = "Cinta perdamaian dan keharusan mempertebal semangat jihad "