name = "Al-Anfaal"
number = 8
[[topics]]
from = 2
to = 4
topic = "Sifat-sifat orang mukmin"

[[topics]]
from = 5
to = 19
topic = "kosong"

[[topics]]
from = 5
to = 19
topic = "Keengganan sebahagian sahabat untuk pergi ke peperangan badar dan pertolongan Allah kepada kaum musl"

[[topics]]
from = 20
to = 30
topic = "Larangan menyalahi perintah-perintah Allah"

[[topics]]
from = 0
to = 0
topic = "kosong"

