name = "At Takwir"
number = 81

[[topics]]
topic = "KETIKA TERJADI PERISTIWA-PERISTIWA BESAR PADA HARI KIAMAT, SETIAP"

[[topics]]
topic = "JIWA TAHU APA YANG TELAH DIKERJAKANNYA DI DUNIA "

[[topics]]
topic = "MUHAMMAD BUKANLAH SEORANG GILA, TAPI RASUL YANG DITURUNKAN AL-QUR'AN"
