name = "Al-Mutaffifin"
number = 83

[[topics]]
from = 1
to = 1
topic = "ANCAMAN TERHADAP ORANG YANG CURANG DALAM MENAKAR DAN MENIMBANG"

[[topics]]
from = 1
to = 1
topic = "KEADAAN ORANG YANG DURHAKA PADA HARI KIAMAT"

[[topics]]
from = 1
to = 1
topic = "KEADAAN ORANG YANG BERBAKTI KEPADA ALLAH PADA HARI KIAMAT"

[[topics]]
from = 1
to = 1
topic = "EJEKAN TERHADAP ORANG MUKMIN DI DUNIA DAN BALASANNYA DI AKHIRAT"

