name = "Al-Mutaffifin"
number = 83

[[topics]]
from = 1
to = 6
topic = "ANCAMAN TERHADAP ORANG YANG CURANG DALAM MENAKAR DAN MENIMBANG"

[[topics]]
from = 7
to = 17
topic = "KEADAAN ORANG YANG DURHAKA PADA HARI KIAMAT"

[[topics]]
from = 18
to = 28
topic = "KEADAAN ORANG YANG BERBAKTI KEPADA ALLAH PADA HARI KIAMAT"

[[topics]]
from = 29
to = 36
topic = "EJEKAN TERHADAP ORANG MUKMIN DI DUNIA DAN BALASANNYA DI AKHIRAT"

