name = "Al-Insyiqaq"
number = 84

[[topics]]
topic = "ORANG MUKMIN MENERIMA CATATAN AMALNYA DI SEBELAH KANAN"

[[topics]]
topic = "ORANG DURHAKA MENERIMA CATATAN AMALNYA DARI BELAKANG DAN AKAN DIMASUKKAN KE NERAKA"

[[topics]]
topic = "MANUSIA MENGALAMI PROSES KEHIDUPAN SECARA BERTAHAP "