name = "Al-Insyiqaq"
number = 84

[[topics]]
from = 1
to = 8
topic = "ORANG MUKMIN MENERIMA CATATAN AMALNYA DI SEBELAH KANAN"

[[topics]]
from = 9
to = 15
topic = "ORANG DURHAKA MENERIMA CATATAN AMALNYA DARI BELAKANG DAN AKAN DIMASUKKAN KE NERAKA"

[[topics]]
from = 16
to = 25
topic = "MANUSIA MENGALAMI PROSES KEHIDUPAN SECARA BERTAHAP "