name = "At-Tariq"
number = 86

[[topics]]
from = 1
to = 4
topic = "Setiap Orang Ada yang Menjaganya"

[[topics]]
from = 5
to = 10
topic = "Allah Kuasa Membangkitkan Manusia"

[[topics]]
from = 11
to = 17
topic = "Al-Quran Pemisah Antara yang Haq dan yang Batil"
