name = "At-Tariq"
number = 86

[[topics]]
topic = "SETIAP ORANG ADA YANG MENJAGANYA"

[[topics]]
topic = "ALLAH KUASA MEMBANGKITKAN MANUSIA "

[[topics]]
topic = "AL-QUR'AN PEMISAH ANTARA YANG HAQ DAN YANG BATIL"
