name = "Al-Fajr"
number = 89

[[topics]]
topic = "ORANG YANG MENENTANG NABI MUHAMMAD PASTI BINASA "

[[topics]]
topic = "KEKAYAAN DAN KEMISKINAN ADALAH UJIAN BAGI HAMBA ALLAH"

[[topics]]
topic = "PENYESALAN MANUSIA PADA HARI KIAMAT"

[[topics]]
topic = "PENGHARGAAN ALLAH TERHADAP MANUSIA YANG SEMPURNA IMANNYA"

