name = "At-Taubah"
number = 9

[[topics]]
from = 1
to = 37
topic = "PENGUMUMAN TENTANG PEMBATALAN PERJANJIAN DAMAI DENGAN KAUM MUSYRIKIN"
    [[topics.subs]]
    from = 1
    to = 4
    text = "Orang Islam terbebas dari tanggung jawab terhadap perjanjian dengan kaum musyrikin"
    [[topics.subs]]
    from = 5
    to = 6
    text = "Pengumuman perang terhadap kaum musyrikin"
    [[topics.subs]]
    from = 7
    to = 15
    text = "Penyebab perjanjian damai dibatalkan"
    [[topics.subs]]
    from = 16
    to = 16
    text = "Ujian keimanan"
    [[topics.subs]]
    from = 17
    to = 24
    text = "Orang yang layak memakmurkan masjid"
    [[topics.subs]]
    from = 25
    to = 29
    text = "Umat Islam mendapat kemenangan dalam berbagai pertempuran"
    [[topics.subs]]
    from = 30
    to = 35
    text = "Kepercayaan orang-orang Yahudi dan Nasrani serta sikap mereka"
    [[topics.subs]]
    from = 36
    to = 37
    text = "Bulan-bulan yang dihormati"

[[topics]]
from = 38
to = 129
topic = "KISAH PERANG TABUK "
    [[topics.subs]]
    from = 38
    to = 43
    text = "Anjuran untuk berjihad "
    [[topics.subs]]
    from = 44
    to = 57
    text = "Hanya orang munafik yang tidak mau berperang"
    [[topics.subs]]
    from = 58
    to = 59
    text = "Sikap orang munafik terhadap pembagian sedekah"
    [[topics.subs]]
    from = 60
    to = 61
    text = "Ketentuan pembagian zakat "
    [[topics.subs]]
    from = 62
    to = 66
    text = "Tuduhan orang munafik terhadap Nabi"
    [[topics.subs]]
    from = 67
    to = 70
    text = "Hasutan orang-orang munafik dan ancaman Allah terhadap mereka "
    [[topics.subs]]
    from = 71
    to = 72
    text = "Anjuran kepada orang-orang mukmin dan janji Allah terhadap mereka"
    [[topics.subs]]
    from = 73
    to = 74
    text = "Keharusan bersikap tegas terhadap orang kafir dan munafik "
    [[topics.subs]]
    from = 75
    to = 78
    text = "Ikrar orang munafik tidak dapat dipercaya"
    [[topics.subs]]
    from = 79
    to = 80
    text = "Kemunafikan adalah dosa yang tidak diampuni Allah "
    [[topics.subs]]
    from = 81
    to = 83
    text = "Keadaan orang-orang munafik yang tidak mau turut berjihad"
    [[topics.subs]]
    from = 84
    to = 85
    text = "Larangan menshalatkan jenazah orang munafik"
    [[topics.subs]]
    from = 86
    to = 90
    text = "Keengganan orang munafik untuk berjihad dan pahala orang yang berjihad"
    [[topics.subs]]
    from = 91
    to = 102
    text = "Uzur yang dibenarkan syariat untuk tidak berjihad"
    [[topics.subs]]
    from = 103
    to = 106
    text = "Keharusan Penguasa memungut zakat "
    [[topics.subs]]
    from = 107
    to = 110
    text = "Keharusan waspada terhadap tipu muslihat orang yang mempergunakan masjid sebagai alatnya "
    [[topics.subs]]
    from = 111
    to = 112
    text = "Penghargaan Allah terhadap para syuhada'"
    [[topics.subs]]
    from = 113
    to = 129
    text = "Larangan memintakan ampun untuk orang musyrik"