name = "At-Taubah"
number = 9
[[topics]]
from = 1
to = 24
topic = "Pengumuman tentang pembatalan perjanjian damai"

[[topics]]
from = 0
to = 0
topic = "kosong"

[[topics]]
from = 71
to = 72
topic = "Anjuran kepada orang-orang mu'min dan janji Allah terhadap mereka"

[[topics]]
from = 128
to = 129
topic = "Tawakal : Berserah setelah berusaha"

