name = "At-Tiin"
number = 95

[[topics]]
from = 1
to = 1
topic = "MANUSIA DICIPTAKAN DALAM BENTUK YANG SEBAIK-BAIKNYA "

[[topics]]
from = 1
to = 1
topic = "YANG MENJADI BAROMETER KEMULIAAN IALAH IMAN DAN AMAL "
